//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alcdiary
    {
        public decimal trz { get; set; }
        public System.DateTime trx { get; set; }
        public decimal referral { get; set; }
        public decimal srno { get; set; }
        public decimal mno { get; set; }
        public System.DateTime addate { get; set; }
        public System.DateTime oaddate { get; set; }
        public decimal interval { get; set; }
        public decimal keyw { get; set; }
        public decimal complby { get; set; }
        public decimal can { get; set; }
        public string n1 { get; set; }
        public string n2 { get; set; }
        public string n3 { get; set; }
        public string n4 { get; set; }
        public string n5 { get; set; }
        public string n6 { get; set; }
        public string n7 { get; set; }
        public Nullable<decimal> au1 { get; set; }
        public Nullable<decimal> au2 { get; set; }
        public Nullable<decimal> au3 { get; set; }
        public Nullable<decimal> au4 { get; set; }
        public Nullable<decimal> au5 { get; set; }
        public Nullable<decimal> au6 { get; set; }
        public Nullable<decimal> au7 { get; set; }
        public Nullable<decimal> sum { get; set; }
        public decimal unusual { get; set; }
        public string user_new { get; set; }
        public System.DateTime user_new_date { get; set; }
        public string user_delete { get; set; }
        public System.DateTime user_delete_date { get; set; }
        public decimal bkno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
