//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BespokeForms
    {
        public string topictype { get; set; }
        public string topicname { get; set; }
        public string parentname { get; set; }
        public int mod_id { get; set; }
        public int order { get; set; }
        public string classname { get; set; }
        public string wbtclass { get; set; }
        public string name { get; set; }
        public string linktext { get; set; }
        public int type { get; set; }
        public decimal referral { get; set; }
        public decimal expanded { get; set; }
        public decimal defmodule { get; set; }
        public decimal topiclink { get; set; }
        public decimal can { get; set; }
        public decimal dipuse { get; set; }
        public decimal axstype { get; set; }
        public int cst { get; set; }
        public decimal srno { get; set; }
        public decimal userdef { get; set; }
        public decimal active { get; set; }
        public decimal history { get; set; }
        public string xmldesign { get; set; }
        public string xmlhistorygrid { get; set; }
        public decimal user_author { get; set; }
        public decimal parentmod_old { get; set; }
        public string wcsfilename { get; set; }
        public decimal version { get; set; }
        public string dcdfilebin { get; set; }
        public string fldfilebin { get; set; }
        public decimal levelpub { get; set; }
        public string servercode { get; set; }
        public decimal autoprint { get; set; }
        public string guid { get; set; }
        public string parentmod { get; set; }
        public decimal addevent { get; set; }
        public decimal locked { get; set; }
        public decimal defetype { get; set; }
        public decimal defdur { get; set; }
        public string defevdate { get; set; }
        public string defkeyw { get; set; }
        public string defrem1 { get; set; }
        public string prjgrp { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string cBespokeTemplate { get; set; }
        public string cFormName { get; set; }
    }
}
