//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carepgp
    {
        public decimal gpno { get; set; }
        public decimal srno { get; set; }
        public decimal pno { get; set; }
        public Nullable<decimal> type { get; set; }
        public Nullable<decimal> can { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public Nullable<decimal> status { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
