//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carepin
    {
        public decimal bkno { get; set; }
        public Nullable<decimal> dexp { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<decimal> vrno { get; set; }
        public decimal srno { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> referral { get; set; }
        public Nullable<decimal> type { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> can { get; set; }
        public string rem2 { get; set; }
        public string rem3 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string rem4 { get; set; }
        public string rem5 { get; set; }
        public string rem6 { get; set; }
    }
}
