//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carep
    {
        public Nullable<decimal> dexp { get; set; }
        public int srno { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int referral { get; set; }
        public int mno { get; set; }
        public Nullable<decimal> caretype { get; set; }
        public Nullable<System.DateTime> crs { get; set; }
        public Nullable<System.DateTime> cre { get; set; }
        public Nullable<System.DateTime> crep { get; set; }
        public Nullable<decimal> crstatus { get; set; }
        public Nullable<decimal> crout { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<System.DateTime> review { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public Nullable<decimal> revdays { get; set; }
        public string rem2 { get; set; }
        public Nullable<System.DateTime> funding { get; set; }
        public Nullable<decimal> hours { get; set; }
        public Nullable<decimal> detox { get; set; }
        public Nullable<decimal> gdr1 { get; set; }
        public Nullable<decimal> gdr2 { get; set; }
        public Nullable<decimal> gdr3 { get; set; }
        public Nullable<decimal> gdr4 { get; set; }
        public Nullable<decimal> gdr5 { get; set; }
        public Nullable<decimal> gdr6 { get; set; }
        public Nullable<decimal> gdr7 { get; set; }
        public Nullable<decimal> gdrs { get; set; }
        public Nullable<System.DateTime> gdrdate { get; set; }
        public Nullable<decimal> gpr1 { get; set; }
        public Nullable<decimal> gpr2 { get; set; }
        public Nullable<decimal> gpr3 { get; set; }
        public Nullable<decimal> gpr4 { get; set; }
        public Nullable<decimal> gpr5 { get; set; }
        public Nullable<decimal> gpr6 { get; set; }
        public Nullable<decimal> gprs { get; set; }
        public Nullable<System.DateTime> gprdate { get; set; }
        public Nullable<decimal> gsr1 { get; set; }
        public Nullable<decimal> gsr2 { get; set; }
        public Nullable<decimal> gsr3 { get; set; }
        public Nullable<decimal> gsr4 { get; set; }
        public Nullable<decimal> gsr5 { get; set; }
        public Nullable<decimal> gsr6 { get; set; }
        public Nullable<decimal> gsrs { get; set; }
        public Nullable<System.DateTime> gsrdate { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public Nullable<decimal> bkno { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public Nullable<System.DateTime> grdates { get; set; }
        public Nullable<System.DateTime> gprdates { get; set; }
        public Nullable<System.DateTime> gsrdates { get; set; }
        public Nullable<decimal> category { get; set; }
        public Nullable<System.DateTime> tac { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public System.DateTime modref { get; set; }
        public System.DateTime firstapp { get; set; }
        public string rem3 { get; set; }
        public string rem4 { get; set; }
        public string rem5 { get; set; }
        public string OPRAGNCY { get; set; }
        public decimal modset { get; set; }
    }
}
