//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carepp
    {
        public Nullable<System.DateTime> crs { get; set; }
        public Nullable<System.DateTime> cre { get; set; }
        public string caretype { get; set; }
        public string crstatus { get; set; }
        public string crout { get; set; }
        public string rem1 { get; set; }
        public string persno { get; set; }
        public Nullable<decimal> revdays { get; set; }
        public Nullable<System.DateTime> review { get; set; }
        public Nullable<System.DateTime> crep { get; set; }
        public string rem2 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public decimal careppid { get; set; }
    }
}
