//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cds3tmp
    {
        public int mno { get; set; }
        public int referral { get; set; }
        public string agency { get; set; }
        public string sn { get; set; }
        public string fn { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public Nullable<decimal> lauth { get; set; }
        public string postcode { get; set; }
        public string ethnic { get; set; }
        public string exserv { get; set; }
        public string persno { get; set; }
        public Nullable<decimal> flang { get; set; }
        public Nullable<decimal> childels { get; set; }
        public Nullable<decimal> childh { get; set; }
        public Nullable<decimal> vadults { get; set; }
        public Nullable<System.DateTime> refd { get; set; }
        public Nullable<decimal> refs { get; set; }
        public string peerment { get; set; }
        public string casemng { get; set; }
        public Nullable<System.DateTime> assessed { get; set; }
        public Nullable<System.DateTime> treatbeg { get; set; }
        public Nullable<System.DateTime> contend { get; set; }
        public Nullable<decimal> reason { get; set; }
        public Nullable<decimal> drug1 { get; set; }
        public Nullable<decimal> dsource1 { get; set; }
        public Nullable<decimal> droute1 { get; set; }
        public Nullable<decimal> dfreq1 { get; set; }
        public Nullable<decimal> dage1 { get; set; }
        public Nullable<decimal> drug2 { get; set; }
        public Nullable<decimal> dsource2 { get; set; }
        public Nullable<decimal> droute2 { get; set; }
        public Nullable<decimal> dfreq2 { get; set; }
        public Nullable<decimal> drug3 { get; set; }
        public Nullable<decimal> dsource3 { get; set; }
        public Nullable<decimal> droute3 { get; set; }
        public Nullable<decimal> dfreq3 { get; set; }
        public string everinj { get; set; }
        public string injected { get; set; }
        public string shared { get; set; }
        public Nullable<decimal> ageinj { get; set; }
        public Nullable<decimal> agetreat { get; set; }
        public Nullable<decimal> weekalc { get; set; }
        public string pregnant { get; set; }
        public string vachepb { get; set; }
        public string vacprov { get; set; }
        public string diagmhi { get; set; }
        public string inpdetox { get; set; }
        public string comdetox { get; set; }
        public string resrehab { get; set; }
        public string someth { get; set; }
        public string sobupren { get; set; }
        public string psychint { get; set; }
        public string pracsup { get; set; }
        public string complact { get; set; }
        public string briefint { get; set; }
        public string harmred { get; set; }
        public string recordid { get; set; }
        public string topid { get; set; }
        public Nullable<System.DateTime> topdate { get; set; }
        public string trstage { get; set; }
        public string alcav { get; set; }
        public string alctotal { get; set; }
        public string opiav { get; set; }
        public string opitotal { get; set; }
        public string craav { get; set; }
        public string cratotal { get; set; }
        public string cocav { get; set; }
        public string coctotal { get; set; }
        public string ampav { get; set; }
        public string amptotal { get; set; }
        public string canav { get; set; }
        public string cantotal { get; set; }
        public string othdrug { get; set; }
        public string othav { get; set; }
        public string othtotal { get; set; }
        public string injtotal { get; set; }
        public string sharetotal { get; set; }
        public string slifttotal { get; set; }
        public string dselltotal { get; set; }
        public string thefttotal { get; set; }
        public string assvtotal { get; set; }
        public string psyhstotal { get; set; }
        public string pworktotal { get; set; }
        public string colltotal { get; set; }
        public string phyhstotal { get; set; }
        public string hprobtotal { get; set; }
        public string risktotal { get; set; }
        public string qlifetotal { get; set; }
        public Nullable<System.DateTime> idstart { get; set; }
        public Nullable<System.DateTime> idend { get; set; }
        public Nullable<System.DateTime> cdstart { get; set; }
        public Nullable<System.DateTime> cdend { get; set; }
        public Nullable<System.DateTime> rrstart { get; set; }
        public Nullable<System.DateTime> rrend { get; set; }
        public Nullable<System.DateTime> sopmstart { get; set; }
        public Nullable<System.DateTime> sopmend { get; set; }
        public Nullable<System.DateTime> sopbstart { get; set; }
        public Nullable<System.DateTime> sopbend { get; set; }
        public Nullable<System.DateTime> pistart { get; set; }
        public Nullable<System.DateTime> piend { get; set; }
        public Nullable<System.DateTime> psstart { get; set; }
        public Nullable<System.DateTime> psend { get; set; }
        public Nullable<System.DateTime> castart { get; set; }
        public Nullable<System.DateTime> caend { get; set; }
        public Nullable<System.DateTime> bistart { get; set; }
        public Nullable<System.DateTime> biend { get; set; }
        public Nullable<System.DateTime> hrstart { get; set; }
        public Nullable<System.DateTime> hrend { get; set; }
        public Nullable<decimal> can { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
