//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chemists
    {
        public int chemist { get; set; }
        public string name { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> status { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string chname { get; set; }
        public string ad1 { get; set; }
        public string ad2 { get; set; }
        public string ad3 { get; set; }
        public string ad4 { get; set; }
        public string ad5 { get; set; }
        public Nullable<decimal> f_left { get; set; }
        public decimal rrag { get; set; }
        public decimal cst { get; set; }
        public string prjgrp { get; set; }
        public string postcode { get; set; }
        public string email { get; set; }
        public string ph_worker_name { get; set; }
        public string fax { get; set; }
        public string worktime { get; set; }
        public string otel { get; set; }
        public Nullable<int> orig_id { get; set; }
        public Nullable<decimal> satclose { get; set; }
        public Nullable<decimal> sunclose { get; set; }
    }
}
