//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class christo
    {
        public Nullable<decimal> dexp { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int referral { get; set; }
        public int srno { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> cissdate { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public Nullable<decimal> evloc { get; set; }
        public Nullable<decimal> interval { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> md1 { get; set; }
        public Nullable<decimal> md2 { get; set; }
        public Nullable<decimal> md3 { get; set; }
        public Nullable<decimal> md4 { get; set; }
        public Nullable<decimal> md5 { get; set; }
        public Nullable<decimal> md6 { get; set; }
        public Nullable<decimal> md7 { get; set; }
        public Nullable<decimal> md8 { get; set; }
        public Nullable<decimal> md9 { get; set; }
        public Nullable<decimal> md10 { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public Nullable<decimal> bkno { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
