//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CJIT_Referral
    {
        public int CJITReferralID { get; set; }
        public int CJITID { get; set; }
        public Nullable<System.DateTime> ReferralDate { get; set; }
        public string ReferralAgency { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string AmendedUser { get; set; }
        public Nullable<System.DateTime> AmendedDate { get; set; }
        public bool RecordDeleted { get; set; }
    }
}
