//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CJIT_Office
    {
        public int CJITOfficeId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Can { get; set; }
        public decimal Cst { get; set; }
        public string Agency { get; set; }
        public decimal PCT { get; set; }
        public string PCT_Name { get; set; }
        public decimal DAT { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string Address_3 { get; set; }
        public string Address_4 { get; set; }
        public string Address_5 { get; set; }
        public string Address_6 { get; set; }
        public string Postcode { get; set; }
        public string Telephone { get; set; }
        public Nullable<decimal> F_left { get; set; }
        public string Prjgrp { get; set; }
        public bool RecordDeleted { get; set; }
    }
}
