//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CJIT
    {
        public int CJITID { get; set; }
        public string ClientReference { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string KeyWorker { get; set; }
        public int EOC { get; set; }
        public string Consent { get; set; }
        public Nullable<int> Agency { get; set; }
        public string PostCode { get; set; }
        public string LAofResidence { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string AccomNeed { get; set; }
        public string Pregnant { get; set; }
        public string OnMAPPA { get; set; }
        public string OnIOMS { get; set; }
        public Nullable<int> TransferFromType { get; set; }
        public string TransferFromLA { get; set; }
        public string TransferFromPrison { get; set; }
        public Nullable<int> TransferToType { get; set; }
        public string TransferToLA { get; set; }
        public string TransferToPrison { get; set; }
        public string Prompt { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public string Offence { get; set; }
        public string Drug1 { get; set; }
        public string Drug2 { get; set; }
        public string Drug3 { get; set; }
        public string DrugRoute { get; set; }
        public string InjectStatus { get; set; }
        public Nullable<int> AlcDays { get; set; }
        public Nullable<decimal> AlUnits { get; set; }
        public Nullable<System.DateTime> CaseloadDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public string ClosureReason { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string AmendedUser { get; set; }
        public Nullable<System.DateTime> AmendedDate { get; set; }
        public bool RecordDeleted { get; set; }
        public string DATofResidence { get; set; }
        public string TransferToDAT { get; set; }
        public string TransferFromDAT { get; set; }
    }
}
