//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CJIT_TOP
    {
        public int CJITTOPID { get; set; }
        public int TOPID { get; set; }
        public int CJITID { get; set; }
        public Nullable<System.DateTime> TOPDate { get; set; }
        public string TreatStage { get; set; }
        public Nullable<int> AlcoholUse { get; set; }
        public Nullable<int> OpiateUse { get; set; }
        public Nullable<int> Consumption { get; set; }
        public Nullable<int> CrackUse { get; set; }
        public Nullable<int> CocaineUse { get; set; }
        public Nullable<int> AmphetamineUse { get; set; }
        public Nullable<int> CannabisUse { get; set; }
        public Nullable<int> OtherDrugUse { get; set; }
        public Nullable<int> IVDrugUse { get; set; }
        public string Sharing { get; set; }
        public Nullable<int> ShopTheft { get; set; }
        public Nullable<int> DrugSelling { get; set; }
        public Nullable<int> OtherTheft { get; set; }
        public Nullable<int> AssaultViolence { get; set; }
        public Nullable<int> PsycholgoicalHealth { get; set; }
        public Nullable<int> PhysicalHealth { get; set; }
        public Nullable<int> LifeQuality { get; set; }
        public Nullable<int> PaidWork { get; set; }
        public Nullable<int> Education { get; set; }
        public string AcuteHousingProb { get; set; }
        public string HousingRisk { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string AmendedUser { get; set; }
        public Nullable<System.DateTime> AmendedDate { get; set; }
        public bool RecordDeleted { get; set; }
    }
}
