//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conh
    {
        public int srno { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> adate { get; set; }
        public Nullable<decimal> type { get; set; }
        public Nullable<decimal> pno { get; set; }
        public Nullable<decimal> consent { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> jointwork { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> prescribing { get; set; }
        public Nullable<decimal> present { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
