//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contacts
    {
        public decimal pno { get; set; }
        public string sn { get; set; }
        public string fn { get; set; }
        public string title { get; set; }
        public Nullable<decimal> type { get; set; }
        public string ad1 { get; set; }
        public string ad2 { get; set; }
        public string ad3 { get; set; }
        public string ad4 { get; set; }
        public string ad5 { get; set; }
        public string post { get; set; }
        public string otel { get; set; }
        public string ftel { get; set; }
        public string htel { get; set; }
        public string gpcode { get; set; }
        public Nullable<decimal> can { get; set; }
        public string gppc { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> pcg { get; set; }
        public Nullable<decimal> gprac { get; set; }
        public string mail { get; set; }
        public Nullable<decimal> rrag { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public decimal trz { get; set; }
        public string prjgrp { get; set; }
    }
}
