//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class criminal
    {
        public int srno { get; set; }
        public Nullable<decimal> dexp { get; set; }
        public Nullable<decimal> flag { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> crimdate { get; set; }
        public Nullable<decimal> arrest { get; set; }
        public Nullable<decimal> station { get; set; }
        public string custody { get; set; }
        public Nullable<System.DateTime> seendw { get; set; }
        public Nullable<System.DateTime> teldw { get; set; }
        public Nullable<System.DateTime> potel { get; set; }
        public Nullable<System.DateTime> assessd { get; set; }
        public Nullable<decimal> can { get; set; }
        public string rem1 { get; set; }
        public Nullable<System.DateTime> treatd { get; set; }
        public Nullable<decimal> tragency { get; set; }
        public Nullable<decimal> assnot { get; set; }
        public string asstime { get; set; }
        public Nullable<decimal> methadone { get; set; }
        public Nullable<decimal> spend { get; set; }
        public Nullable<decimal> prevconv { get; set; }
        public Nullable<decimal> prison { get; set; }
        public Nullable<decimal> arrold { get; set; }
        public string location { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
