//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class diplegal
    {
        public int lrno { get; set; }
        public Nullable<int> srno { get; set; }
        public Nullable<decimal> cjitoffence { get; set; }
        public Nullable<decimal> cjitstatus { get; set; }
        public Nullable<decimal> bailsubj { get; set; }
        public Nullable<decimal> warrants { get; set; }
        public Nullable<decimal> otheroutst { get; set; }
        public Nullable<decimal> commorder { get; set; }
        public Nullable<decimal> onlicence { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> mostser { get; set; }
        public string otherrem { get; set; }
        public Nullable<decimal> serious { get; set; }
        public Nullable<decimal> sentlen { get; set; }
        public Nullable<decimal> oftype1 { get; set; }
        public Nullable<decimal> oftype2 { get; set; }
        public Nullable<decimal> oftype3 { get; set; }
        public Nullable<decimal> oftype4 { get; set; }
        public Nullable<decimal> oftype5 { get; set; }
        public Nullable<decimal> oftype6 { get; set; }
        public Nullable<decimal> oftype7 { get; set; }
        public Nullable<decimal> oftype8 { get; set; }
        public Nullable<decimal> oftype9 { get; set; }
        public Nullable<decimal> oftype10 { get; set; }
        public Nullable<decimal> oftype11 { get; set; }
        public Nullable<decimal> oftype12 { get; set; }
        public Nullable<decimal> oftype13 { get; set; }
        public Nullable<decimal> oftype14 { get; set; }
        public Nullable<decimal> oftype15 { get; set; }
        public Nullable<decimal> oftype16 { get; set; }
        public Nullable<decimal> oftype17 { get; set; }
        public Nullable<decimal> oftype18 { get; set; }
        public Nullable<decimal> oftype19 { get; set; }
        public Nullable<decimal> oftype20 { get; set; }
        public Nullable<decimal> oftype21 { get; set; }
        public Nullable<decimal> oftype22 { get; set; }
        public Nullable<decimal> oftype23 { get; set; }
        public string ostatus { get; set; }
        public Nullable<decimal> dexp { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> prisonstat { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
