//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disdest
    {
        public int DISDEST1 { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> CAN { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> RRAG { get; set; }
        public Nullable<decimal> F_LEFT { get; set; }
        public string NDTMS { get; set; }
        public string USER_NEW { get; set; }
        public Nullable<System.DateTime> USER_NEW_DATE { get; set; }
        public string USER_DELETE { get; set; }
        public Nullable<System.DateTime> USER_DELETE_DATE { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal cst { get; set; }
        public string prjgrp { get; set; }
        public Nullable<int> orig_id { get; set; }
    }
}
