//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class drugs
    {
        public Nullable<decimal> dexp { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int srno { get; set; }
        public int referral { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> added { get; set; }
        public Nullable<int> drug { get; set; }
        public Nullable<int> route { get; set; }
        public Nullable<int> freq { get; set; }
        public string quantity { get; set; }
        public Nullable<decimal> prescr { get; set; }
        public string duration { get; set; }
        public Nullable<decimal> fuse { get; set; }
        public Nullable<System.DateTime> ldate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> drusage { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> inject { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public string user_upd { get; set; }
        public Nullable<int> usagetr { get; set; }
        public Nullable<int> routetr { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal q1 { get; set; }
        public decimal q2 { get; set; }
        public decimal q3 { get; set; }
        public decimal q4 { get; set; }
        public decimal q5 { get; set; }
        public decimal q6 { get; set; }
        public decimal q7 { get; set; }
        public decimal q8 { get; set; }
        public decimal q9 { get; set; }
        public decimal q10 { get; set; }
        public string auditalc { get; set; }
        public string bingeday { get; set; }
        public decimal smokests { get; set; }
        public decimal treatgol { get; set; }
        public System.DateTime sdate { get; set; }
        public decimal source { get; set; }
        public int userid { get; set; }
    }
}
