//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dstatus
    {
        public int status { get; set; }
        public string name { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> rrag { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public decimal cst { get; set; }
        public string prjgrp { get; set; }
        public Nullable<int> orig_id { get; set; }
        public decimal f_left { get; set; }
    }
}
