//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailacc
    {
        public decimal srno { get; set; }
        public string name { get; set; }
        public decimal can { get; set; }
        public decimal f_left { get; set; }
        public string user_new { get; set; }
        public System.DateTime user_new_date { get; set; }
        public string user_delete { get; set; }
        public System.DateTime user_delete_date { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string mailserver { get; set; }
        public Nullable<decimal> port { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public decimal cst { get; set; }
        public string email { get; set; }
        public decimal ssl { get; set; }
    }
}
