//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailh
    {
        public decimal srno { get; set; }
        public System.DateTime senddate { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public decimal emailacc { get; set; }
        public decimal emailtpl { get; set; }
        public string sender { get; set; }
        public string subject { get; set; }
        public string receiver { get; set; }
        public decimal contents { get; set; }
        public decimal bkno { get; set; }
        public decimal blk { get; set; }
        public decimal can { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> referral { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string docuname { get; set; }
        public string doctype { get; set; }
        public string docdescr { get; set; }
        public string docfile { get; set; }
        public string filename { get; set; }
        public string docext { get; set; }
    }
}
