//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class etype
    {
        public decimal etype1 { get; set; }
        public string name { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> status { get; set; }
        public Nullable<decimal> zno { get; set; }
        public string ztitle { get; set; }
        public Nullable<decimal> zro { get; set; }
        public Nullable<decimal> rrag { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> astype { get; set; }
        public Nullable<decimal> fastype { get; set; }
        public Nullable<decimal> nta { get; set; }
        public Nullable<decimal> ev1 { get; set; }
        public Nullable<decimal> ev2 { get; set; }
        public Nullable<decimal> duration { get; set; }
        public Nullable<decimal> appointment { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public Nullable<decimal> ntatriage { get; set; }
        public Nullable<decimal> cpst { get; set; }
        public Nullable<decimal> dthca { get; set; }
        public Nullable<decimal> face2face { get; set; }
        public Nullable<decimal> treatype { get; set; }
        public string user_upd { get; set; }
        public Nullable<decimal> tmstart { get; set; }
        public Nullable<decimal> superec { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> f_left { get; set; }
        public decimal color { get; set; }
        public string colorx { get; set; }
        public decimal nca { get; set; }
        public decimal cst { get; set; }
        public string prjgrp { get; set; }
        public decimal initass { get; set; }
        public decimal fullass { get; set; }
        public Nullable<int> orig_id { get; set; }
        public decimal tier { get; set; }
    }
}
