//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        public Nullable<decimal> dexp { get; set; }
        public Nullable<decimal> flag { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int bkno { get; set; }
        public Nullable<System.DateTime> evdate { get; set; }
        public string tto { get; set; }
        public string tfrom { get; set; }
        public int mno { get; set; }
        public decimal estatus { get; set; }
        public decimal etype { get; set; }
        public decimal keyw { get; set; }
        public Nullable<decimal> duration { get; set; }
        public decimal evloc { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> nhs1 { get; set; }
        public Nullable<decimal> nhs2 { get; set; }
        public Nullable<decimal> nhs3 { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public Nullable<decimal> withint { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> casestat { get; set; }
        public Nullable<decimal> p1 { get; set; }
        public Nullable<decimal> p2 { get; set; }
        public Nullable<decimal> p3 { get; set; }
        public Nullable<decimal> p4 { get; set; }
        public Nullable<decimal> p5 { get; set; }
        public Nullable<decimal> p6 { get; set; }
        public Nullable<decimal> p7 { get; set; }
        public Nullable<decimal> p8 { get; set; }
        public Nullable<System.DateTime> p1d { get; set; }
        public Nullable<System.DateTime> p2d { get; set; }
        public Nullable<System.DateTime> p3d { get; set; }
        public Nullable<System.DateTime> p4d { get; set; }
        public Nullable<System.DateTime> p5d { get; set; }
        public Nullable<System.DateTime> p6d { get; set; }
        public Nullable<decimal> p5p { get; set; }
        public Nullable<decimal> cjit { get; set; }
        public Nullable<decimal> carat { get; set; }
        public string p5po { get; set; }
        public Nullable<decimal> er1 { get; set; }
        public Nullable<decimal> er2 { get; set; }
        public Nullable<decimal> attinit { get; set; }
        public Nullable<decimal> attinityes { get; set; }
        public string attinityeso { get; set; }
        public Nullable<System.DateTime> attydate { get; set; }
        public Nullable<decimal> attinitno { get; set; }
        public string attinitnoo { get; set; }
        public Nullable<System.DateTime> attndate { get; set; }
        public Nullable<decimal> folreq { get; set; }
        public Nullable<decimal> folatt { get; set; }
        public Nullable<decimal> foldatatt { get; set; }
        public Nullable<decimal> drrcare { get; set; }
        public Nullable<decimal> newprov1 { get; set; }
        public string newprov1o { get; set; }
        public Nullable<System.DateTime> newagdate1 { get; set; }
        public Nullable<decimal> newprov2 { get; set; }
        public string newprov2o { get; set; }
        public Nullable<System.DateTime> newagdate2 { get; set; }
        public Nullable<decimal> cjitcare { get; set; }
        public Nullable<decimal> cpdrawn { get; set; }
        public Nullable<System.DateTime> datecp { get; set; }
        public Nullable<System.DateTime> nocpdate { get; set; }
        public Nullable<decimal> nocpreas { get; set; }
        public string nocpreaso { get; set; }
        public Nullable<decimal> rengreas { get; set; }
        public string rengreaso { get; set; }
        public Nullable<decimal> primhdel { get; set; }
        public Nullable<System.DateTime> primhdate { get; set; }
        public Nullable<decimal> fadvdel { get; set; }
        public Nullable<System.DateTime> fadvdate { get; set; }
        public Nullable<decimal> comhdel { get; set; }
        public Nullable<System.DateTime> comhdate { get; set; }
        public Nullable<decimal> hadvdel { get; set; }
        public Nullable<System.DateTime> hadvdate { get; set; }
        public Nullable<decimal> peersdel { get; set; }
        public Nullable<System.DateTime> peersdate { get; set; }
        public Nullable<decimal> leisdel { get; set; }
        public Nullable<System.DateTime> leisdate { get; set; }
        public Nullable<decimal> supedudel { get; set; }
        public Nullable<System.DateTime> supedudate { get; set; }
        public Nullable<decimal> fsupdel { get; set; }
        public Nullable<System.DateTime> fsupdate { get; set; }
        public Nullable<decimal> supempdel { get; set; }
        public Nullable<System.DateTime> supempdate { get; set; }
        public Nullable<decimal> osupdel { get; set; }
        public Nullable<System.DateTime> osupdate { get; set; }
        public string osuptext { get; set; }
        public Nullable<decimal> harmdel { get; set; }
        public Nullable<System.DateTime> harmdate { get; set; }
        public Nullable<decimal> overmdel { get; set; }
        public Nullable<System.DateTime> overmdate { get; set; }
        public Nullable<decimal> rapidpdel { get; set; }
        public Nullable<System.DateTime> rapidpdate { get; set; }
        public Nullable<decimal> gwdel { get; set; }
        public Nullable<System.DateTime> gwdate { get; set; }
        public Nullable<decimal> strucdel { get; set; }
        public Nullable<System.DateTime> strucdate { get; set; }
        public Nullable<decimal> bialcdel { get; set; }
        public Nullable<System.DateTime> bialcdate { get; set; }
        public Nullable<decimal> crackdel { get; set; }
        public Nullable<System.DateTime> crackdate { get; set; }
        public Nullable<decimal> appres { get; set; }
        public decimal referral { get; set; }
        public System.DateTime sms_dt { get; set; }
        public string sms_tel { get; set; }
        public string sms_user { get; set; }
        public decimal sms_userid { get; set; }
        public decimal keyw2 { get; set; }
        public decimal keyw3 { get; set; }
        public decimal keyw4 { get; set; }
        public decimal keyw5 { get; set; }
        public decimal gid { get; set; }
        public decimal rctype { get; set; }
        public decimal rcdays { get; set; }
        public decimal rccnt { get; set; }
        public decimal rid { get; set; }
        public System.DateTime rsdate { get; set; }
        public decimal nca { get; set; }
        public System.DateTime redate { get; set; }
        public decimal recpat { get; set; }
        public decimal recpatday { get; set; }
        public decimal recpatdayn { get; set; }
        public decimal recpatwekn { get; set; }
        public decimal recpatwekd1 { get; set; }
        public decimal recpatwekd2 { get; set; }
        public decimal recpatwekd3 { get; set; }
        public decimal recpatwekd4 { get; set; }
        public decimal recpatwekd5 { get; set; }
        public decimal recpatwekd6 { get; set; }
        public decimal recpatwekd7 { get; set; }
        public decimal recpatmon { get; set; }
        public decimal recpatmonday { get; set; }
        public decimal recpatmonmon { get; set; }
        public decimal recpatmonthe { get; set; }
        public decimal recpatmondayw { get; set; }
        public decimal recpatyea { get; set; }
        public decimal recpatyeamonth { get; set; }
        public decimal recpatyeaday { get; set; }
        public decimal recpatyeathe { get; set; }
        public decimal recpatyeadayw { get; set; }
        public decimal recpatrange { get; set; }
        public decimal recpatrangenoc { get; set; }
        public System.DateTime recpatrangedate { get; set; }
        public decimal recdiff { get; set; }
        public decimal etype2 { get; set; }
        public string sms_text { get; set; }
        public decimal visitac { get; set; }
        public string rem2 { get; set; }
        public string rem3 { get; set; }
        public string rem4 { get; set; }
    }
}
