//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVOUTPMH
    {
        public decimal EVOUTPMH1 { get; set; }
        public string NAME { get; set; }
        public decimal CAN { get; set; }
        public decimal STATUS { get; set; }
        public decimal RRAG { get; set; }
        public string USER_NEW { get; set; }
        public System.DateTime USER_NEW_DATE { get; set; }
        public string USER_DELETE { get; set; }
        public System.DateTime USER_DELETE_DATE { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> f_left { get; set; }
        public decimal cst { get; set; }
        public string prjgrp { get; set; }
        public Nullable<decimal> ORIG_ID { get; set; }
        public string user_upd { get; set; }
    }
}
