//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVOUTSFH
    {
        public int BKNO { get; set; }
        public int MNO { get; set; }
        public System.DateTime ADDED { get; set; }
        public decimal SERVTYPE { get; set; }
        public string REM1 { get; set; }
        public decimal CAN { get; set; }
        public decimal EVOUTSF { get; set; }
        public decimal ISSUE { get; set; }
        public decimal SRNO { get; set; }
        public System.DateTime DATE { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string user_upd { get; set; }
    }
}
