//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class global
    {
        public int gid { get; set; }
        public short nout { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public int cst { get; set; }
        public int f_left { get; set; }
        public int can { get; set; }
        public int nzntanotapproved { get; set; }
        public int nAut26 { get; set; }
        public int nAut17 { get; set; }
        public int nAut13 { get; set; }
        public int nAut11 { get; set; }
        public int nExportTo { get; set; }
        public string name { get; set; }
        public int nLetterFormat { get; set; }
    }
}
