//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hep
    {
        public decimal TRZ { get; set; }
        public System.DateTime TRX { get; set; }
        public decimal MNO { get; set; }
        public decimal REFERRAL { get; set; }
        public System.DateTime HEPAV1 { get; set; }
        public System.DateTime HEPAV2 { get; set; }
        public System.DateTime HEPAV3 { get; set; }
        public System.DateTime HEPAIC { get; set; }
        public decimal HEPAIMM { get; set; }
        public System.DateTime HEPABOOST { get; set; }
        public System.DateTime HEPABOOST2 { get; set; }
        public System.DateTime HEPABOOST3 { get; set; }
        public System.DateTime HEPBV1 { get; set; }
        public System.DateTime HEPBV2 { get; set; }
        public System.DateTime HEPBV3 { get; set; }
        public System.DateTime HEPBBOOST { get; set; }
        public System.DateTime HEPBBOOST2 { get; set; }
        public System.DateTime HEPBBOOST3 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
