//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hepbhiv
    {
        public decimal SRNO { get; set; }
        public decimal TRZ { get; set; }
        public System.DateTime TRX { get; set; }
        public decimal MNO { get; set; }
        public decimal REFERRAL { get; set; }
        public string REM1 { get; set; }
        public decimal HIV1 { get; set; }
        public System.DateTime HIV2 { get; set; }
        public decimal HIV3 { get; set; }
        public System.DateTime HIV3D { get; set; }
        public decimal HIV3A { get; set; }
        public decimal HIV4 { get; set; }
        public System.DateTime HIV4D { get; set; }
        public decimal CAN { get; set; }
        public decimal bkno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
