//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hepbb
    {
        public decimal SRNO { get; set; }
        public decimal TRZ { get; set; }
        public System.DateTime TRX { get; set; }
        public decimal MNO { get; set; }
        public decimal REFERRAL { get; set; }
        public string REM1 { get; set; }
        public decimal HEPB1 { get; set; }
        public System.DateTime HEPB2 { get; set; }
        public decimal HEPB3A { get; set; }
        public decimal HEPB3B { get; set; }
        public decimal HEPB3C { get; set; }
        public decimal HEPB4 { get; set; }
        public System.DateTime HEPB4D { get; set; }
        public decimal CAN { get; set; }
        public decimal bkno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
