//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hepb
    {
        public Nullable<decimal> dexp { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> hp1d { get; set; }
        public Nullable<System.DateTime> hp2d { get; set; }
        public Nullable<System.DateTime> hp3d { get; set; }
        public Nullable<System.DateTime> hp4d { get; set; }
        public Nullable<System.DateTime> hp5d { get; set; }
        public Nullable<System.DateTime> hp6d { get; set; }
        public Nullable<decimal> hp7 { get; set; }
        public Nullable<System.DateTime> hp7d { get; set; }
        public Nullable<System.DateTime> hp8d { get; set; }
        public Nullable<System.DateTime> hp9d { get; set; }
        public Nullable<System.DateTime> hp10d { get; set; }
        public Nullable<System.DateTime> hp11d { get; set; }
        public Nullable<decimal> hp12 { get; set; }
        public Nullable<System.DateTime> hp13d { get; set; }
        public Nullable<System.DateTime> hp14d { get; set; }
        public string rem1 { get; set; }
        public Nullable<System.DateTime> hepcd { get; set; }
        public Nullable<decimal> hiv { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public Nullable<decimal> hepct { get; set; }
        public Nullable<decimal> hepcr { get; set; }
        public Nullable<System.DateTime> hivdate { get; set; }
        public Nullable<decimal> hivr { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> hepcdate { get; set; }
        public Nullable<decimal> hepcstat { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public int hepbid { get; set; }
        public decimal HEPCPOS { get; set; }
        public string HPB1M { get; set; }
        public string HPB1Y { get; set; }
        public string HPB2M { get; set; }
        public string HPB2Y { get; set; }
        public string HPCM { get; set; }
        public string HPCY { get; set; }
        public System.DateTime hp15d { get; set; }
        public System.DateTime hp16d { get; set; }
        public System.DateTime hivd { get; set; }
        public decimal hepc { get; set; }
        public decimal hepb1 { get; set; }
        public System.DateTime hepbd { get; set; }
        public string hivm { get; set; }
        public string hivy { get; set; }
    }
}
