//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hepbc
    {
        public decimal SRNO { get; set; }
        public decimal TRZ { get; set; }
        public System.DateTime TRX { get; set; }
        public decimal MNO { get; set; }
        public string REM1 { get; set; }
        public decimal HEPC1 { get; set; }
        public System.DateTime HEPC2 { get; set; }
        public decimal HEPC3 { get; set; }
        public System.DateTime HEPC4 { get; set; }
        public decimal HEPC5 { get; set; }
        public decimal HEPC6 { get; set; }
        public System.DateTime HEPC6D { get; set; }
        public decimal CAN { get; set; }
        public decimal bkno { get; set; }
        public decimal referral { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
