//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDTables
    {
        public Nullable<decimal> tableID { get; set; }
        public string tablename { get; set; }
        public string IDFldName { get; set; }
        public byte lut { get; set; }
        public string FK1 { get; set; }
        public string FK2 { get; set; }
        public string FK3 { get; set; }
    }
}
