//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inject
    {
        public decimal trz { get; set; }
        public System.DateTime trx { get; set; }
        public int srno { get; set; }
        public int mno { get; set; }
        public System.DateTime injdate { get; set; }
        public decimal keyw { get; set; }
        public decimal can { get; set; }
        public decimal priinj { get; set; }
        public decimal secinj { get; set; }
        public Nullable<decimal> timday { get; set; }
        public Nullable<decimal> timwek { get; set; }
        public Nullable<decimal> injyer { get; set; }
        public Nullable<decimal> injmon { get; set; }
        public decimal injthem { get; set; }
        public decimal workinsp { get; set; }
        public decimal ocuser { get; set; }
        public decimal bbv { get; set; }
        public decimal abstin { get; set; }
        public decimal citric { get; set; }
        public decimal retpol { get; set; }
        public string prorem { get; set; }
        public decimal maindrug { get; set; }
        public decimal secdrug { get; set; }
        public decimal share { get; set; }
        public string dused { get; set; }
        public string presbody { get; set; }
        public decimal spoons { get; set; }
        public decimal filters { get; set; }
        public decimal water { get; set; }
        public string courserem { get; set; }
        public string stertype { get; set; }
        public string bloodpres { get; set; }
        public System.DateTime iftdate { get; set; }
        public decimal iftresult { get; set; }
        public decimal vaccin { get; set; }
        public decimal overdose { get; set; }
        public decimal ois1 { get; set; }
        public decimal ois2 { get; set; }
        public decimal ois3 { get; set; }
        public decimal ois4 { get; set; }
        public decimal ois5 { get; set; }
        public decimal ois6 { get; set; }
        public decimal ois7 { get; set; }
        public decimal ois8 { get; set; }
        public decimal office { get; set; }
        public decimal bkno { get; set; }
        public decimal referral { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal ADVICE { get; set; }
        public decimal USENS4W { get; set; }
        public decimal SHARE4W { get; set; }
        public Nullable<decimal> ALCUNITS { get; set; }
        public string REMINJT { get; set; }
        public decimal BADVICE { get; set; }
        public decimal INTREAT { get; set; }
        public decimal SCRIPTED { get; set; }
        public Nullable<decimal> OVERHIST { get; set; }
        public decimal WARNGIVE { get; set; }
        public decimal OVERRISK { get; set; }
        public decimal NTA31 { get; set; }
        public decimal HEPC { get; set; }
        public System.DateTime HEPCDATE { get; set; }
        public decimal HEPCFOL { get; set; }
        public string REM3 { get; set; }
    }
}
