//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class keyw
    {
        public int keyw1 { get; set; }
        public string name { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> status { get; set; }
        public Nullable<System.DateTime> adate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<decimal> f_position { get; set; }
        public Nullable<decimal> f_left { get; set; }
        public string room { get; set; }
        public Nullable<decimal> rno { get; set; }
        public Nullable<decimal> rrag { get; set; }
        public string kwf { get; set; }
        public Nullable<decimal> kkk { get; set; }
        public Nullable<System.DateTime> dol { get; set; }
        public Nullable<System.DateTime> doj { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public decimal appsched { get; set; }
        public decimal bhwork { get; set; }
        public decimal mon { get; set; }
        public decimal tue { get; set; }
        public decimal wed { get; set; }
        public decimal thu { get; set; }
        public decimal fri { get; set; }
        public decimal sat { get; set; }
        public decimal sun { get; set; }
        public string mon_tfrom { get; set; }
        public string mon_tto { get; set; }
        public string tue_tfrom { get; set; }
        public string tue_tto { get; set; }
        public string wed_tfrom { get; set; }
        public string wed_tto { get; set; }
        public string thu_tfrom { get; set; }
        public string thu_tto { get; set; }
        public string fri_tfrom { get; set; }
        public string fri_tto { get; set; }
        public string sat_tfrom { get; set; }
        public string sat_tto { get; set; }
        public string sun_tfrom { get; set; }
        public string sun_tto { get; set; }
        public decimal smsauth { get; set; }
        public decimal rrag2 { get; set; }
        public decimal rrag3 { get; set; }
        public decimal rrag4 { get; set; }
        public decimal rrag5 { get; set; }
        public string jobtitle { get; set; }
        public decimal cst { get; set; }
        public string prjgrp { get; set; }
        public Nullable<int> orig_id { get; set; }
    }
}
