//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class knah
    {
        public decimal srno { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public decimal knareason { get; set; }
        public decimal keyw { get; set; }
        public System.DateTime dfrom { get; set; }
        public System.DateTime dto { get; set; }
        public string tfrom { get; set; }
        public string tto { get; set; }
        public decimal can { get; set; }
        public string rem1 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> tac { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
    }
}
