//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lettersh
    {
        public decimal srno { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public Nullable<decimal> trz { get; set; }
        public decimal mno { get; set; }
        public decimal referral { get; set; }
        public System.DateTime senddate { get; set; }
        public decimal dcd_id { get; set; }
        public decimal bkno { get; set; }
        public string rem1 { get; set; }
        public decimal can { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string username { get; set; }
        public string letter { get; set; }
    }
}
