//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogFile
    {
        public int LogID { get; set; }
        public string LogTableName { get; set; }
        public Nullable<int> LogRowID { get; set; }
        public string LogFieldName { get; set; }
        public string LogOldValue { get; set; }
        public string LogNewValue { get; set; }
        public string LogOperation { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
        public string LogUserName { get; set; }
        public Nullable<decimal> LogClientMno { get; set; }
    }
}
