//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lookup_data
    {
        public int lookup_id { get; set; }
        public string lookup_type { get; set; }
        public string lookup_key { get; set; }
        public string lookup_value { get; set; }
        public string lookup_nta_code { get; set; }
        public string prjgrp { get; set; }
        public Nullable<bool> lookup_obsolete { get; set; }
        public bool lookup_deleted { get; set; }
    }
}
