//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lookups
    {
        public int type { get; set; }
        public int lookup_id { get; set; }
        public int orderby { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public decimal nta { get; set; }
        public decimal cds { get; set; }
        public string classname { get; set; }
        public string tablename { get; set; }
        public string icon { get; set; }
        public decimal axstype { get; set; }
        public decimal cst { get; set; }
        public decimal tplfield { get; set; }
        public decimal f_left { get; set; }
        public decimal can { get; set; }
        public string guid { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
