//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maudrug
    {
        public Nullable<decimal> dexp { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public decimal drno { get; set; }
        public Nullable<decimal> srno { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> status { get; set; }
        public Nullable<decimal> drug { get; set; }
        public Nullable<decimal> route { get; set; }
        public Nullable<decimal> days { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string arem1 { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
