//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class maud
    {
        public Nullable<decimal> dexp { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int referral { get; set; }
        public int srno { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> mapdate { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public Nullable<decimal> evloc { get; set; }
        public Nullable<decimal> interval { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> md1 { get; set; }
        public Nullable<decimal> md2 { get; set; }
        public Nullable<decimal> md3 { get; set; }
        public Nullable<decimal> md4 { get; set; }
        public Nullable<decimal> md5 { get; set; }
        public Nullable<decimal> md6 { get; set; }
        public Nullable<decimal> md7 { get; set; }
        public Nullable<decimal> md8 { get; set; }
        public Nullable<decimal> md9 { get; set; }
        public Nullable<decimal> md10 { get; set; }
        public Nullable<decimal> md11 { get; set; }
        public Nullable<decimal> md12 { get; set; }
        public Nullable<decimal> md13 { get; set; }
        public Nullable<decimal> md14 { get; set; }
        public string md15 { get; set; }
        public string md16 { get; set; }
        public string md17 { get; set; }
        public string md18 { get; set; }
        public string md19 { get; set; }
        public string md20 { get; set; }
        public string md21 { get; set; }
        public Nullable<decimal> md22 { get; set; }
        public Nullable<decimal> md23 { get; set; }
        public Nullable<decimal> md24 { get; set; }
        public Nullable<decimal> md25 { get; set; }
        public Nullable<decimal> md26 { get; set; }
        public Nullable<decimal> md27 { get; set; }
        public Nullable<decimal> md28 { get; set; }
        public Nullable<decimal> md29 { get; set; }
        public Nullable<decimal> md30 { get; set; }
        public Nullable<decimal> md31 { get; set; }
        public Nullable<decimal> md32 { get; set; }
        public Nullable<decimal> md33 { get; set; }
        public Nullable<decimal> md34 { get; set; }
        public Nullable<decimal> md35 { get; set; }
        public Nullable<decimal> md36 { get; set; }
        public Nullable<decimal> md37 { get; set; }
        public Nullable<decimal> md38 { get; set; }
        public Nullable<decimal> md39 { get; set; }
        public Nullable<decimal> md40 { get; set; }
        public Nullable<decimal> md41 { get; set; }
        public Nullable<decimal> md42 { get; set; }
        public Nullable<decimal> md43 { get; set; }
        public Nullable<decimal> md44 { get; set; }
        public Nullable<decimal> md45 { get; set; }
        public Nullable<decimal> md46 { get; set; }
        public Nullable<decimal> md47 { get; set; }
        public Nullable<decimal> md48 { get; set; }
        public Nullable<decimal> md49 { get; set; }
        public Nullable<decimal> md50 { get; set; }
        public Nullable<decimal> md51 { get; set; }
        public Nullable<decimal> md52 { get; set; }
        public Nullable<decimal> md53 { get; set; }
        public Nullable<decimal> md54 { get; set; }
        public Nullable<decimal> md55 { get; set; }
        public Nullable<decimal> md56 { get; set; }
        public Nullable<decimal> md57 { get; set; }
        public Nullable<decimal> md58 { get; set; }
        public Nullable<decimal> md59 { get; set; }
        public Nullable<decimal> md60 { get; set; }
        public Nullable<decimal> md61 { get; set; }
        public Nullable<decimal> md62 { get; set; }
        public Nullable<decimal> md63 { get; set; }
        public Nullable<decimal> md64 { get; set; }
        public Nullable<decimal> md65 { get; set; }
        public Nullable<decimal> md66 { get; set; }
        public Nullable<decimal> md67 { get; set; }
        public Nullable<decimal> md68 { get; set; }
        public Nullable<decimal> md69 { get; set; }
        public Nullable<decimal> md70 { get; set; }
        public Nullable<decimal> md71 { get; set; }
        public Nullable<decimal> md72 { get; set; }
        public Nullable<decimal> md73 { get; set; }
        public Nullable<decimal> md74 { get; set; }
        public Nullable<decimal> md75 { get; set; }
        public Nullable<decimal> md76 { get; set; }
        public Nullable<decimal> md77 { get; set; }
        public Nullable<decimal> md78 { get; set; }
        public Nullable<decimal> md79 { get; set; }
        public Nullable<decimal> md80 { get; set; }
        public Nullable<decimal> md81 { get; set; }
        public Nullable<decimal> md82 { get; set; }
        public Nullable<decimal> md83 { get; set; }
        public Nullable<decimal> md84 { get; set; }
        public Nullable<decimal> md85 { get; set; }
        public Nullable<decimal> md86 { get; set; }
        public Nullable<decimal> md87 { get; set; }
        public Nullable<decimal> md88 { get; set; }
        public Nullable<decimal> md89 { get; set; }
        public Nullable<decimal> md90 { get; set; }
        public Nullable<decimal> md91 { get; set; }
        public Nullable<decimal> md92 { get; set; }
        public Nullable<decimal> md93 { get; set; }
        public Nullable<decimal> md94 { get; set; }
        public Nullable<decimal> md95 { get; set; }
        public Nullable<decimal> md96 { get; set; }
        public Nullable<decimal> md97 { get; set; }
        public Nullable<decimal> md98 { get; set; }
        public Nullable<decimal> md99 { get; set; }
        public Nullable<decimal> md100 { get; set; }
        public Nullable<decimal> md101 { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public Nullable<decimal> bkno { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
