//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdl_axs
    {
        public Nullable<decimal> module_id { get; set; }
        public string modulename { get; set; }
        public string user_upd { get; set; }
        public Nullable<decimal> axstype { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> orderby { get; set; }
        public Nullable<decimal> can { get; set; }
        public decimal clrel { get; set; }
    }
}
