//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msgboard
    {
        public decimal srno { get; set; }
        public System.DateTime msgdate { get; set; }
        public string msgtext { get; set; }
        public Nullable<decimal> replyto { get; set; }
        public Nullable<decimal> can { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal cst { get; set; }
        public decimal user_id { get; set; }
        public Nullable<decimal> mno { get; set; }
    }
}
