//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nedx
    {
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public Nullable<decimal> dexp { get; set; }
        public int srno { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> nxdate { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> js1 { get; set; }
        public Nullable<decimal> js2 { get; set; }
        public Nullable<decimal> js3 { get; set; }
        public Nullable<decimal> js4 { get; set; }
        public Nullable<decimal> js5 { get; set; }
        public Nullable<decimal> jb1 { get; set; }
        public Nullable<decimal> jb2 { get; set; }
        public Nullable<decimal> jb3 { get; set; }
        public Nullable<decimal> jb4 { get; set; }
        public Nullable<decimal> jb5 { get; set; }
        public Nullable<decimal> jb6 { get; set; }
        public Nullable<decimal> jb7 { get; set; }
        public Nullable<decimal> jn1 { get; set; }
        public Nullable<decimal> jn2 { get; set; }
        public Nullable<decimal> jn3 { get; set; }
        public Nullable<decimal> jn4 { get; set; }
        public Nullable<decimal> jn20 { get; set; }
        public Nullable<decimal> jo1 { get; set; }
        public Nullable<decimal> jo2 { get; set; }
        public Nullable<decimal> jo3 { get; set; }
        public Nullable<decimal> jo4 { get; set; }
        public Nullable<decimal> jo5 { get; set; }
        public Nullable<decimal> jo6 { get; set; }
        public Nullable<decimal> jo7 { get; set; }
        public Nullable<decimal> jo8 { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> bkno { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public Nullable<decimal> js6 { get; set; }
        public Nullable<decimal> js7 { get; set; }
        public Nullable<decimal> js8 { get; set; }
        public Nullable<decimal> js9 { get; set; }
        public Nullable<decimal> js10 { get; set; }
        public Nullable<decimal> js11 { get; set; }
        public Nullable<decimal> js12 { get; set; }
        public Nullable<decimal> js13 { get; set; }
        public Nullable<decimal> jr1 { get; set; }
        public Nullable<decimal> jr2 { get; set; }
        public Nullable<decimal> jr3 { get; set; }
        public Nullable<decimal> jr4 { get; set; }
        public Nullable<decimal> jr5 { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public Nullable<decimal> evloc { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> jr6 { get; set; }
        public Nullable<decimal> jr7 { get; set; }
        public Nullable<decimal> jr8 { get; set; }
        public Nullable<decimal> jr9 { get; set; }
        public Nullable<decimal> jr10 { get; set; }
        public Nullable<decimal> jr11 { get; set; }
        public Nullable<decimal> jo9 { get; set; }
        public decimal referral { get; set; }
        public decimal office { get; set; }
        public string tfrom { get; set; }
        public decimal mobile { get; set; }
        public decimal js14 { get; set; }
        public string advice { get; set; }
        public decimal otherint { get; set; }
        public string rem2 { get; set; }
        public Nullable<decimal> jr20 { get; set; }
        public Nullable<decimal> js15 { get; set; }
        public Nullable<decimal> js16 { get; set; }
        public Nullable<decimal> js17 { get; set; }
        public Nullable<decimal> jo10 { get; set; }
        public Nullable<decimal> jo11 { get; set; }
        public Nullable<decimal> jo12 { get; set; }
        public Nullable<decimal> jo13 { get; set; }
        public Nullable<decimal> js18 { get; set; }
        public Nullable<decimal> js19 { get; set; }
        public Nullable<decimal> js20 { get; set; }
    }
}
