//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nix
    {
        public decimal JS1 { get; set; }
        public decimal JS2 { get; set; }
        public decimal JS3 { get; set; }
        public decimal JS4 { get; set; }
        public decimal JS5 { get; set; }
        public decimal JB1 { get; set; }
        public decimal JB2 { get; set; }
        public decimal JB3 { get; set; }
        public decimal JB4 { get; set; }
        public decimal JB5 { get; set; }
        public decimal JB6 { get; set; }
        public decimal JB7 { get; set; }
        public decimal JN1 { get; set; }
        public decimal JN2 { get; set; }
        public decimal JN3 { get; set; }
        public decimal JN4 { get; set; }
        public decimal JN20 { get; set; }
        public decimal JO1 { get; set; }
        public decimal JO2 { get; set; }
        public decimal JO3 { get; set; }
        public decimal JO4 { get; set; }
        public decimal JO5 { get; set; }
        public decimal JO6 { get; set; }
        public decimal JO7 { get; set; }
        public decimal JO8 { get; set; }
        public decimal CAN { get; set; }
        public decimal BKNO { get; set; }
        public decimal JS6 { get; set; }
        public decimal JS7 { get; set; }
        public decimal JS8 { get; set; }
        public decimal JS9 { get; set; }
        public decimal JS10 { get; set; }
        public decimal JS11 { get; set; }
        public decimal JS12 { get; set; }
        public decimal JS13 { get; set; }
        public decimal JR1 { get; set; }
        public decimal JR2 { get; set; }
        public decimal JR3 { get; set; }
        public decimal JR4 { get; set; }
        public decimal JR5 { get; set; }
        public decimal JR10 { get; set; }
        public decimal JR20 { get; set; }
        public decimal JS1S { get; set; }
        public decimal JS2S { get; set; }
        public decimal JS3S { get; set; }
        public decimal JS4S { get; set; }
        public decimal JS5S { get; set; }
        public decimal JS6S { get; set; }
        public decimal JS7S { get; set; }
        public decimal JS8S { get; set; }
        public decimal JS9S { get; set; }
        public decimal JS10S { get; set; }
        public decimal JS11S { get; set; }
        public decimal JS12S { get; set; }
        public decimal JS13S { get; set; }
        public decimal JO1S { get; set; }
        public decimal JO2S { get; set; }
        public decimal JO6S { get; set; }
        public decimal JO7S { get; set; }
        public decimal JB1S { get; set; }
        public decimal JB2S { get; set; }
        public decimal JB3S { get; set; }
        public decimal JB4S { get; set; }
        public decimal JB5S { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
