//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ntamdslist
    {
        public string finitial { get; set; }
        public string sinitial { get; set; }
        public string dob { get; set; }
        public string sex { get; set; }
        public string ethnic { get; set; }
        public string nation { get; set; }
        public string refld { get; set; }
        public string agncy { get; set; }
        public string client { get; set; }
        public string clientid { get; set; }
        public string episodid { get; set; }
        public string consent { get; set; }
        public string prevtr { get; set; }
        public string pc { get; set; }
        public string accmneed { get; set; }
        public string prntstat { get; set; }
        public string AACLWY { get; set; }
        public string dat { get; set; }
        public string pct { get; set; }
        public string la { get; set; }
        public string gpptce { get; set; }
        public string drug1 { get; set; }
        public string drug1age { get; set; }
        public string droute { get; set; }
        public string drug2 { get; set; }
        public string drug3 { get; set; }
        public string rfls { get; set; }
        public string triaged { get; set; }
        public string cplandt { get; set; }
        public string injstat { get; set; }
        public string childwth { get; set; }
        public string pregnant { get; set; }
        public string alcddays { get; set; }
        public string alcunits { get; set; }
        public string dualdiag { get; set; }
        public string hepctstd { get; set; }
        public string hepcstat { get; set; }
        public string hepctd { get; set; }
        public string hepbvac { get; set; }
        public string hepbstat { get; set; }
        public string hlcassdt { get; set; }
        public string topcc { get; set; }
        public string disd { get; set; }
        public string disrsn { get; set; }
        public string pbr { get; set; }
        public string cplxas { get; set; }
        public string modal { get; set; }
        public string refmoddt { get; set; }
        public string MODSET { get; set; }
        public string modid { get; set; }
        public string faomoddt { get; set; }
        public string modst { get; set; }
        public string modend { get; set; }
        public string modexit { get; set; }
        public string SUBMODS { get; set; }
        public string TITS { get; set; }
        public string TOPS { get; set; }
        public string YPORS { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<int> srno { get; set; }
        public decimal prjgrp { get; set; }
    }
}
