//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class office
    {
        public int office1 { get; set; }
        public string name { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> status { get; set; }
        public Nullable<decimal> zno { get; set; }
        public string ztitle { get; set; }
        public Nullable<decimal> zro { get; set; }
        public Nullable<decimal> rrag { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public string agency { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> f_left { get; set; }
        public Nullable<decimal> rx1 { get; set; }
        public decimal pct { get; set; }
        public decimal dat { get; set; }
        public string ad1 { get; set; }
        public string ad2 { get; set; }
        public string ad3 { get; set; }
        public string ad4 { get; set; }
        public string ad5 { get; set; }
        public string ad6 { get; set; }
        public decimal cst { get; set; }
        public string prjgrp { get; set; }
        public Nullable<decimal> modset { get; set; }
        public Nullable<int> orig_id { get; set; }
        public string postcode { get; set; }
        public string otel { get; set; }
        public string pctname { get; set; }
        public string pctcode { get; set; }
        public int yps { get; set; }
    }
}
