//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class outstat
    {
        public string rtitle { get; set; }
        public Nullable<decimal> rtot { get; set; }
        public Nullable<decimal> rrag { get; set; }
        public Nullable<decimal> rperc { get; set; }
        public Nullable<decimal> rtot2 { get; set; }
        public Nullable<decimal> rtos1 { get; set; }
        public Nullable<decimal> rtos2 { get; set; }
        public Nullable<decimal> rtos3 { get; set; }
        public Nullable<decimal> days { get; set; }
        public Nullable<decimal> lodays { get; set; }
        public Nullable<decimal> hidays { get; set; }
        public Nullable<decimal> avdays { get; set; }
        public Nullable<decimal> loflag { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public decimal sflag { get; set; }
        public decimal uflag { get; set; }
        public decimal partflag { get; set; }
        public decimal spartflag { get; set; }
        public string groupname { get; set; }
        public decimal showchart { get; set; }
    }
}
