//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parcap
    {
        public decimal dexp { get; set; }
        public decimal trz { get; set; }
        public System.DateTime trx { get; set; }
        public decimal srno { get; set; }
        public decimal referral { get; set; }
        public decimal mno { get; set; }
        public decimal ppdu1 { get; set; }
        public decimal ppdu2 { get; set; }
        public decimal ppdu3 { get; set; }
        public decimal ppdu4 { get; set; }
        public decimal ppdu5 { get; set; }
        public string ppdu1rem { get; set; }
        public string ppdu2rem { get; set; }
        public string ppdu3rem { get; set; }
        public string ppdu4rem { get; set; }
        public string ppdu5rem { get; set; }
        public string ppdurem { get; set; }
        public decimal ahe1 { get; set; }
        public decimal ahe2 { get; set; }
        public decimal ahe3 { get; set; }
        public decimal ahe4 { get; set; }
        public decimal ahe5 { get; set; }
        public decimal ahe6 { get; set; }
        public decimal ahe7 { get; set; }
        public decimal ahe8 { get; set; }
        public string ahe1rem { get; set; }
        public string ahe2rem { get; set; }
        public string ahe3rem { get; set; }
        public string ahe4rem { get; set; }
        public string ahe5rem { get; set; }
        public string ahe6rem { get; set; }
        public string ahe7rem { get; set; }
        public string ahe8rem { get; set; }
        public string aherem { get; set; }
        public decimal pbn1 { get; set; }
        public decimal pbn2 { get; set; }
        public decimal pbn3 { get; set; }
        public decimal pbn4 { get; set; }
        public decimal pbn5 { get; set; }
        public string pbn1rem { get; set; }
        public string pbn2rem { get; set; }
        public string pbn3rem { get; set; }
        public string pbn4rem { get; set; }
        public string pbn5rem { get; set; }
        public string pbnrem { get; set; }
        public decimal pd1 { get; set; }
        public decimal pd2 { get; set; }
        public decimal pd3 { get; set; }
        public decimal pd4 { get; set; }
        public decimal pd5 { get; set; }
        public decimal pd6 { get; set; }
        public decimal pd7 { get; set; }
        public string pd1rem { get; set; }
        public string pd2rem { get; set; }
        public string pd3rem { get; set; }
        public string pd4rem { get; set; }
        public string pd5rem { get; set; }
        public string pd6rem { get; set; }
        public string pd7rem { get; set; }
        public string pdrem { get; set; }
        public decimal hr1 { get; set; }
        public decimal hr2 { get; set; }
        public decimal hr3 { get; set; }
        public decimal hr4 { get; set; }
        public decimal hr5 { get; set; }
        public string hr1rem { get; set; }
        public string hr2rem { get; set; }
        public string hr3rem { get; set; }
        public string hr4rem { get; set; }
        public string hr5rem { get; set; }
        public string hrrem { get; set; }
        public decimal fsnss1 { get; set; }
        public decimal fsnss2 { get; set; }
        public decimal fsnss3 { get; set; }
        public decimal fsnss4 { get; set; }
        public string fsnss1rem { get; set; }
        public string fsnss2rem { get; set; }
        public string fsnss3rem { get; set; }
        public string fsnss4rem { get; set; }
        public string fsnssrem { get; set; }
        public decimal pps1 { get; set; }
        public decimal pps2 { get; set; }
        public decimal pps3 { get; set; }
        public string pps1rem { get; set; }
        public string pps2rem { get; set; }
        public string pps3rem { get; set; }
        public string ppsrem { get; set; }
        public string ocspirem { get; set; }
        public string osfrem { get; set; }
        public string actionrem { get; set; }
        public System.DateTime parcdate { get; set; }
        public System.DateTime reviewdate { get; set; }
        public decimal keyw { get; set; }
        public string user_upd { get; set; }
        public System.DateTime dtalter { get; set; }
        public decimal can { get; set; }
        public decimal bkno { get; set; }
        public decimal score { get; set; }
    }
}
