//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class passh
    {
        public Nullable<decimal> user_id { get; set; }
        public string oldpass { get; set; }
        public string newpass { get; set; }
        public Nullable<System.DateTime> dtshift { get; set; }
        public int srno { get; set; }
        public Nullable<System.DateTime> user_upd { get; set; }
    }
}
