//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pcevents
    {
        public decimal trz { get; set; }
        public System.DateTime trx { get; set; }
        public int bkno { get; set; }
        public System.DateTime evdate { get; set; }
        public string tto { get; set; }
        public string tfrom { get; set; }
        public int mnop { get; set; }
        public int estatus { get; set; }
        public int etype { get; set; }
        public int keyw { get; set; }
        public int keyw2 { get; set; }
        public int keyw3 { get; set; }
        public int keyw4 { get; set; }
        public int keyw5 { get; set; }
        public decimal duration { get; set; }
        public int evloc { get; set; }
        public string rem1 { get; set; }
        public decimal can { get; set; }
        public decimal cost { get; set; }
        public string user_new { get; set; }
        public System.DateTime user_new_date { get; set; }
        public string user_delete { get; set; }
        public System.DateTime user_delete_date { get; set; }
        public decimal withint { get; set; }
        public string user_upd { get; set; }
        public System.DateTime dtalter { get; set; }
        public decimal etype2 { get; set; }
        public decimal evspec { get; set; }
        public System.DateTime sms_dt { get; set; }
        public string sms_tel { get; set; }
        public string sms_user { get; set; }
        public decimal sms_userid { get; set; }
        public Nullable<decimal> mno { get; set; }
    }
}
