//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prjgrps
    {
        public decimal prjgrp { get; set; }
        public string name { get; set; }
        public Nullable<decimal> mastergrp { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> isgroup { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> f_left { get; set; }
        public decimal cst { get; set; }
        public decimal smsacc { get; set; }
        public decimal emailacc { get; set; }
    }
}
