//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qslist
    {
        public Nullable<decimal> critid { get; set; }
        public string sessionid { get; set; }
        public Nullable<decimal> userid { get; set; }
        public string title { get; set; }
        public Nullable<decimal> can { get; set; }
        public string flag { get; set; }
        public string stype { get; set; }
        public string pname { get; set; }
        public Nullable<decimal> pvalue { get; set; }
        public Nullable<decimal> pvalue2 { get; set; }
        public string fldname { get; set; }
        public string fldname1 { get; set; }
        public Nullable<System.DateTime> pdate1 { get; set; }
        public Nullable<System.DateTime> pdate2 { get; set; }
        public string pname2 { get; set; }
        public Nullable<decimal> test222 { get; set; }
        public Nullable<decimal> xflag { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public decimal repid { get; set; }
        public decimal scid { get; set; }
        public decimal addparam { get; set; }
    }
}
