//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class referralwl
    {
        public int referralwl1 { get; set; }
        public int REFERRAL { get; set; }
        public Nullable<int> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal trz { get; set; }
        public System.DateTime trx { get; set; }
        public decimal casemng { get; set; }
        public decimal exserv { get; set; }
        public decimal peerment { get; set; }
        public System.DateTime assessed { get; set; }
        public System.DateTime initcont { get; set; }
        public decimal prevrefs { get; set; }
        public Nullable<decimal> spendav { get; set; }
        public decimal vachepb { get; set; }
        public decimal immstat { get; set; }
        public decimal vacprov { get; set; }
        public decimal otherdhi { get; set; }
        public decimal diagmhi { get; set; }
        public decimal srmhi { get; set; }
        public decimal phi { get; set; }
        public string odhitext { get; set; }
        public decimal td1 { get; set; }
        public decimal td2 { get; set; }
        public decimal td3 { get; set; }
        public decimal td4 { get; set; }
        public decimal td5 { get; set; }
        public decimal td6 { get; set; }
        public decimal supcon { get; set; }
        public decimal resreh { get; set; }
        public decimal resdet { get; set; }
        public decimal ps1 { get; set; }
        public decimal ps2 { get; set; }
        public decimal pd1 { get; set; }
        public decimal pd2 { get; set; }
        public decimal subststs { get; set; }
        public Nullable<int> subst_pri { get; set; }
        public Nullable<int> subst_sec { get; set; }
        public Nullable<int> subst_tre { get; set; }
        public Nullable<int> agerefd { get; set; }
        public Nullable<int> ageclosed { get; set; }
    }
}
