//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refs
    {
        public int refs1 { get; set; }
        public string name { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> status { get; set; }
        public Nullable<decimal> zno { get; set; }
        public string ztitle { get; set; }
        public Nullable<decimal> zro { get; set; }
        public Nullable<decimal> rrag { get; set; }
        public string ndtms { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public string user_upd { get; set; }
        public Nullable<decimal> authref { get; set; }
        public string ad1 { get; set; }
        public string ad2 { get; set; }
        public string ad3 { get; set; }
        public string ad4 { get; set; }
        public string otel { get; set; }
        public string mobiletel { get; set; }
        public string ertel { get; set; }
        public string emailbox { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> f_left { get; set; }
        public string cds { get; set; }
        public decimal cst { get; set; }
        public string prjgrp { get; set; }
        public Nullable<int> orig_id { get; set; }
    }
}
