//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reports
    {
        public decimal srno { get; set; }
        public decimal module_id { get; set; }
        public string tplname { get; set; }
        public string name { get; set; }
        public string repname { get; set; }
        public string func { get; set; }
        public decimal can { get; set; }
        public decimal reptype { get; set; }
        public decimal azoptionrq { get; set; }
        public decimal cst { get; set; }
        public decimal userdef { get; set; }
        public Nullable<decimal> cutype { get; set; }
        public string grag { get; set; }
        public string gragdata { get; set; }
        public string partrename { get; set; }
        public string custom_field { get; set; }
        public string custom_field_cols { get; set; }
        public string qslist { get; set; }
        public string qfilter { get; set; }
        public string qorder { get; set; }
        public decimal sctype { get; set; }
        public decimal active { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal HideEmptyRowCol { get; set; }
    }
}
