//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sadq
    {
        public decimal dexp { get; set; }
        public decimal trz { get; set; }
        public System.DateTime trx { get; set; }
        public decimal srno { get; set; }
        public decimal referral { get; set; }
        public decimal mno { get; set; }
        public decimal score { get; set; }
        public decimal q1 { get; set; }
        public decimal q2 { get; set; }
        public decimal q3 { get; set; }
        public decimal q4 { get; set; }
        public decimal q5 { get; set; }
        public decimal q6 { get; set; }
        public decimal q7 { get; set; }
        public decimal q8 { get; set; }
        public decimal q9 { get; set; }
        public decimal q10 { get; set; }
        public decimal q11 { get; set; }
        public decimal q12 { get; set; }
        public decimal q13 { get; set; }
        public decimal q14 { get; set; }
        public decimal q15 { get; set; }
        public decimal q16 { get; set; }
        public decimal q17 { get; set; }
        public decimal q18 { get; set; }
        public decimal q19 { get; set; }
        public decimal q20 { get; set; }
        public string rem1 { get; set; }
        public System.DateTime sadqdate { get; set; }
        public decimal keyw { get; set; }
        public string user_upd { get; set; }
        public System.DateTime dtalter { get; set; }
        public decimal can { get; set; }
        public decimal bkno { get; set; }
        public decimal month { get; set; }
        public decimal year { get; set; }
    }
}
