//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sainsbury
    {
        public decimal sainsbury1 { get; set; }
        public decimal REFERRAL { get; set; }
        public decimal s1 { get; set; }
        public decimal s2 { get; set; }
        public decimal s3 { get; set; }
        public decimal s4 { get; set; }
        public decimal s5 { get; set; }
        public decimal s6 { get; set; }
        public decimal s7 { get; set; }
        public decimal s8 { get; set; }
        public decimal s9 { get; set; }
        public decimal s10 { get; set; }
        public decimal s11 { get; set; }
        public decimal s12 { get; set; }
        public decimal s13 { get; set; }
        public decimal s14 { get; set; }
        public string sothers { get; set; }
        public string srem { get; set; }
        public decimal n1 { get; set; }
        public decimal n2 { get; set; }
        public decimal n3 { get; set; }
        public decimal n4 { get; set; }
        public decimal n5 { get; set; }
        public decimal n6 { get; set; }
        public decimal n7 { get; set; }
        public decimal n8 { get; set; }
        public decimal n9 { get; set; }
        public decimal n10 { get; set; }
        public decimal n11 { get; set; }
        public decimal n12 { get; set; }
        public decimal n13 { get; set; }
        public decimal n14 { get; set; }
        public string nothers { get; set; }
        public string nrem { get; set; }
        public decimal av1 { get; set; }
        public decimal av2 { get; set; }
        public decimal av3 { get; set; }
        public decimal av4 { get; set; }
        public decimal av5 { get; set; }
        public decimal av6 { get; set; }
        public decimal av7 { get; set; }
        public decimal av8 { get; set; }
        public decimal av9 { get; set; }
        public decimal av10 { get; set; }
        public decimal av11 { get; set; }
        public decimal av12 { get; set; }
        public decimal av13 { get; set; }
        public decimal av14 { get; set; }
        public string avothers { get; set; }
        public string avrem { get; set; }
        public decimal o1 { get; set; }
        public decimal o2 { get; set; }
        public decimal o3 { get; set; }
        public decimal o4 { get; set; }
        public decimal o5 { get; set; }
        public decimal o6 { get; set; }
        public decimal o7 { get; set; }
        public decimal o8 { get; set; }
        public decimal o9 { get; set; }
        public decimal o10 { get; set; }
        public decimal o11 { get; set; }
        public decimal o12 { get; set; }
        public decimal o13 { get; set; }
        public decimal o14 { get; set; }
        public decimal o15 { get; set; }
        public decimal o16 { get; set; }
        public string oothers { get; set; }
        public string orem { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal trz { get; set; }
        public System.DateTime trx { get; set; }
    }
}
