//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scbulk
    {
        public decimal rollbck { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public Nullable<System.DateTime> bstart { get; set; }
        public Nullable<System.DateTime> bend { get; set; }
        public string fp10 { get; set; }
        public string keyw { get; set; }
        public string gp { get; set; }
        public string chemist { get; set; }
        public string drug { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> can { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string pct { get; set; }
        public string locality { get; set; }
        public string pdf { get; set; }
    }
}
