//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scdrug
    {
        public int scdrug1 { get; set; }
        public string name { get; set; }
        public Nullable<decimal> strength { get; set; }
        public Nullable<decimal> scunit { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> status { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> rrag { get; set; }
        public Nullable<decimal> beaker { get; set; }
        public Nullable<decimal> discost { get; set; }
        public Nullable<decimal> unitcost { get; set; }
        public Nullable<decimal> condrug { get; set; }
        public Nullable<decimal> concost { get; set; }
        public Nullable<decimal> fp10 { get; set; }
        public Nullable<decimal> nta { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> maxdose { get; set; }
        public Nullable<decimal> f_left { get; set; }
        public decimal maxdays { get; set; }
        public decimal cst { get; set; }
        public string prjgrp { get; set; }
        public decimal scdrugtype { get; set; }
        public decimal strength2 { get; set; }
        public Nullable<int> orig_id { get; set; }
        public Nullable<decimal> contd { get; set; }
    }
}
