//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scriptdays
    {
        public Nullable<decimal> scriptno { get; set; }
        public Nullable<decimal> dayid { get; set; }
        public Nullable<decimal> scdayid { get; set; }
        public Nullable<decimal> disp_date { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<decimal> sdose { get; set; }
        public Nullable<decimal> bdisp_date { get; set; }
        public Nullable<decimal> bsdose { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public decimal scdaysid { get; set; }
    }
}
