//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scriterions_nodip
    {
        public Nullable<int> sctype { get; set; }
        public int scid { get; set; }
        public int orderno { get; set; }
        public string name { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
        public string tblname { get; set; }
        public string contname { get; set; }
        public decimal can { get; set; }
        public decimal mause { get; set; }
        public decimal dipuse { get; set; }
        public string datatype { get; set; }
        public string fldname { get; set; }
        public decimal cst { get; set; }
        public string infotype { get; set; }
        public string lutname { get; set; }
        public string lutpk { get; set; }
        public string getradio { get; set; }
        public decimal width { get; set; }
        public string Ctype { get; set; }
        public decimal rrag_start { get; set; }
        public decimal rrag_total { get; set; }
        public decimal rrag_nr { get; set; }
        public decimal rtype { get; set; }
        public string vfp_fldname { get; set; }
        public decimal tplfield { get; set; }
        public string guid { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
