//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scriptsb
    {
        public Nullable<decimal> @checked { get; set; }
        public Nullable<decimal> rollbck { get; set; }
        public Nullable<decimal> scriptno { get; set; }
        public decimal srno { get; set; }
        public Nullable<decimal> scnumber { get; set; }
        public string name { get; set; }
        public string script { get; set; }
        public Nullable<decimal> goprint { get; set; }
        public string screg { get; set; }
        public Nullable<decimal> bkno { get; set; }
        public Nullable<decimal> blk { get; set; }
        public Nullable<System.DateTime> psd { get; set; }
        public Nullable<System.DateTime> pse { get; set; }
        public string printed { get; set; }
        public Nullable<decimal> days { get; set; }
        public Nullable<decimal> dose { get; set; }
        public Nullable<decimal> reduct { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> chscript { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
    }
}
