//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scripts
    {
        public int rollbck { get; set; }
        public Nullable<int> rollbckx { get; set; }
        public int scriptno { get; set; }
        public int bkno { get; set; }
        public Nullable<decimal> blk { get; set; }
        public Nullable<decimal> brad { get; set; }
        public Nullable<decimal> bflag { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> sdue { get; set; }
        public Nullable<decimal> scdrug { get; set; }
        public Nullable<System.DateTime> psd { get; set; }
        public Nullable<System.DateTime> pse { get; set; }
        public Nullable<System.DateTime> printed { get; set; }
        public Nullable<decimal> cycle { get; set; }
        public Nullable<decimal> days { get; set; }
        public Nullable<decimal> dose { get; set; }
        public Nullable<decimal> opend { get; set; }
        public Nullable<decimal> fp10 { get; set; }
        public Nullable<decimal> dispense { get; set; }
        public Nullable<decimal> disdaily { get; set; }
        public Nullable<decimal> rem2 { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> pdisp { get; set; }
        public Nullable<decimal> chemist { get; set; }
        public Nullable<decimal> can { get; set; }
        public string rm1 { get; set; }
        public Nullable<decimal> rm2 { get; set; }
        public Nullable<decimal> redweek { get; set; }
        public string rem3 { get; set; }
        public Nullable<decimal> prepnext { get; set; }
        public Nullable<decimal> signat { get; set; }
        public Nullable<decimal> reduct { get; set; }
        public Nullable<decimal> rm3 { get; set; }
        public Nullable<decimal> dayred { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<System.DateTime> posted { get; set; }
        public Nullable<decimal> bankhol { get; set; }
        public Nullable<decimal> bankflas { get; set; }
        public Nullable<decimal> beaker { get; set; }
        public Nullable<decimal> discost { get; set; }
        public Nullable<decimal> supercon { get; set; }
        public Nullable<decimal> dubprint { get; set; }
        public string vtotal { get; set; }
        public Nullable<decimal> childscript { get; set; }
        public Nullable<decimal> mindose { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string autorem { get; set; }
        public Nullable<decimal> destroyed { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> nextdue { get; set; }
        public string vunit { get; set; }
        public Nullable<decimal> redinctype { get; set; }
        public Nullable<decimal> redtype { get; set; }
        public Nullable<decimal> inctype { get; set; }
        public Nullable<decimal> incdose { get; set; }
        public Nullable<decimal> maxdose { get; set; }
        public Nullable<decimal> redmds { get; set; }
        public Nullable<decimal> incmds { get; set; }
        public Nullable<decimal> redstart { get; set; }
        public Nullable<decimal> lastdose { get; set; }
        public Nullable<decimal> redperiod { get; set; }
        public Nullable<decimal> incperiod { get; set; }
        public Nullable<System.DateTime> datered { get; set; }
        public decimal @void { get; set; }
        public decimal referral { get; set; }
        public Nullable<decimal> d1 { get; set; }
        public Nullable<decimal> d2 { get; set; }
        public Nullable<decimal> d3 { get; set; }
        public Nullable<decimal> d4 { get; set; }
        public Nullable<decimal> d5 { get; set; }
        public Nullable<decimal> d6 { get; set; }
        public Nullable<decimal> d7 { get; set; }
        public Nullable<decimal> d8 { get; set; }
        public Nullable<decimal> d9 { get; set; }
        public Nullable<decimal> d10 { get; set; }
        public Nullable<decimal> d11 { get; set; }
        public Nullable<decimal> d12 { get; set; }
        public Nullable<decimal> d13 { get; set; }
        public Nullable<decimal> d14 { get; set; }
        public Nullable<decimal> d15 { get; set; }
        public Nullable<decimal> d16 { get; set; }
        public Nullable<decimal> d17 { get; set; }
        public Nullable<decimal> d18 { get; set; }
        public Nullable<decimal> d19 { get; set; }
        public Nullable<decimal> d20 { get; set; }
        public Nullable<decimal> d21 { get; set; }
        public Nullable<decimal> d22 { get; set; }
        public Nullable<decimal> d23 { get; set; }
        public Nullable<decimal> d24 { get; set; }
        public Nullable<decimal> d25 { get; set; }
        public Nullable<decimal> d26 { get; set; }
        public Nullable<decimal> d27 { get; set; }
        public Nullable<decimal> d28 { get; set; }
        public decimal scdayid { get; set; }
        public Nullable<decimal> hd1 { get; set; }
        public Nullable<decimal> hd2 { get; set; }
        public Nullable<decimal> hd3 { get; set; }
        public Nullable<decimal> hd4 { get; set; }
        public Nullable<decimal> hd5 { get; set; }
        public Nullable<decimal> hd6 { get; set; }
        public Nullable<decimal> hd7 { get; set; }
        public Nullable<decimal> hd8 { get; set; }
        public Nullable<decimal> hd9 { get; set; }
        public Nullable<decimal> hd10 { get; set; }
        public Nullable<decimal> hd11 { get; set; }
        public Nullable<decimal> hd12 { get; set; }
        public Nullable<decimal> hd13 { get; set; }
        public Nullable<decimal> hd14 { get; set; }
        public Nullable<decimal> hd15 { get; set; }
        public Nullable<decimal> hd16 { get; set; }
        public Nullable<decimal> hd17 { get; set; }
        public Nullable<decimal> hd18 { get; set; }
        public Nullable<decimal> hd19 { get; set; }
        public Nullable<decimal> hd20 { get; set; }
        public Nullable<decimal> hd21 { get; set; }
        public Nullable<decimal> hd22 { get; set; }
        public Nullable<decimal> hd23 { get; set; }
        public Nullable<decimal> hd24 { get; set; }
        public Nullable<decimal> hd25 { get; set; }
        public Nullable<decimal> hd26 { get; set; }
        public Nullable<decimal> hd27 { get; set; }
        public Nullable<decimal> hd28 { get; set; }
        public Nullable<decimal> bd1 { get; set; }
        public Nullable<decimal> bd2 { get; set; }
        public Nullable<decimal> bd3 { get; set; }
        public Nullable<decimal> bd4 { get; set; }
        public Nullable<decimal> bd5 { get; set; }
        public Nullable<decimal> bd6 { get; set; }
        public Nullable<decimal> bd7 { get; set; }
        public Nullable<decimal> bd8 { get; set; }
        public Nullable<decimal> bd9 { get; set; }
        public Nullable<decimal> bd10 { get; set; }
        public Nullable<decimal> bd11 { get; set; }
        public Nullable<decimal> bd12 { get; set; }
        public Nullable<decimal> bd13 { get; set; }
        public Nullable<decimal> bd14 { get; set; }
        public Nullable<decimal> bd15 { get; set; }
        public Nullable<decimal> bd16 { get; set; }
        public Nullable<decimal> bd17 { get; set; }
        public Nullable<decimal> bd18 { get; set; }
        public Nullable<decimal> bd19 { get; set; }
        public Nullable<decimal> bd20 { get; set; }
        public Nullable<decimal> bd21 { get; set; }
        public Nullable<decimal> bd22 { get; set; }
        public Nullable<decimal> bd23 { get; set; }
        public Nullable<decimal> bd24 { get; set; }
        public Nullable<decimal> bd25 { get; set; }
        public Nullable<decimal> bd26 { get; set; }
        public Nullable<decimal> bd27 { get; set; }
        public Nullable<decimal> bd28 { get; set; }
        public decimal haschild { get; set; }
        public decimal cycles { get; set; }
        public Nullable<decimal> parentscript { get; set; }
        public decimal cycleno { get; set; }
        public System.DateTime cycleend { get; set; }
        public int bkno_ver { get; set; }
        public decimal scdrug_old { get; set; }
        public decimal doccodes { get; set; }
        public Nullable<decimal> cltype { get; set; }
        public Nullable<decimal> remtype { get; set; }
        public Nullable<decimal> rm4 { get; set; }
        public Nullable<decimal> missrem { get; set; }
        public Nullable<decimal> suprem { get; set; }
        public Nullable<decimal> disprem { get; set; }
    }
}
