//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sctypes_nodip
    {
        public decimal sctype { get; set; }
        public Nullable<decimal> orderno { get; set; }
        public string name { get; set; }
        public decimal dipuse { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal cst { get; set; }
        public decimal rtype { get; set; }
        public decimal ismaster { get; set; }
        public decimal parenttype { get; set; }
        public string tblname { get; set; }
        public decimal masterparent { get; set; }
        public decimal can { get; set; }
        public string spname { get; set; }
        public decimal mod_id { get; set; }
        public string guid { get; set; }
        public int rootno { get; set; }
    }
}
