//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shealth
    {
        public decimal flag { get; set; }
        public decimal trj { get; set; }
        public decimal dexp { get; set; }
        public decimal trz { get; set; }
        public System.DateTime trx { get; set; }
        public decimal srno { get; set; }
        public decimal mno { get; set; }
        public decimal referral { get; set; }
        public decimal office { get; set; }
        public System.DateTime shdate { get; set; }
        public decimal keyw { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> js1 { get; set; }
        public Nullable<decimal> js2 { get; set; }
        public Nullable<decimal> js3 { get; set; }
        public Nullable<decimal> js4 { get; set; }
        public Nullable<decimal> js5 { get; set; }
        public Nullable<decimal> js6 { get; set; }
        public Nullable<decimal> js7 { get; set; }
        public Nullable<decimal> js8 { get; set; }
        public Nullable<decimal> js9 { get; set; }
        public Nullable<decimal> js10 { get; set; }
        public Nullable<decimal> js11 { get; set; }
        public Nullable<decimal> js12 { get; set; }
        public Nullable<decimal> js13 { get; set; }
        public Nullable<decimal> js14 { get; set; }
        public Nullable<decimal> js15 { get; set; }
        public Nullable<decimal> js16 { get; set; }
        public Nullable<decimal> jo1 { get; set; }
        public Nullable<decimal> jo2 { get; set; }
        public Nullable<decimal> jo3 { get; set; }
        public Nullable<decimal> jo11 { get; set; }
        public Nullable<decimal> jo12 { get; set; }
        public Nullable<decimal> jo13 { get; set; }
        public decimal can { get; set; }
        public decimal tfrom { get; set; }
        public decimal pregnancy { get; set; }
        public System.DateTime chlamyd { get; set; }
        public decimal bkno { get; set; }
        public decimal working { get; set; }
        public decimal gontest { get; set; }
        public decimal syphtest { get; set; }
        public decimal hivtest { get; set; }
        public decimal chltest { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
