//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smsbulkh
    {
        public decimal blk { get; set; }
        public System.DateTime dtstart { get; set; }
        public System.DateTime dtend { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public System.DateTime blkdate { get; set; }
        public decimal smsacc { get; set; }
        public decimal bkno { get; set; }
        public decimal can { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal sent { get; set; }
        public decimal fail { get; set; }
        public decimal smstpl { get; set; }
    }
}
