//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class smsh
    {
        public decimal srno { get; set; }
        public System.DateTime senddate { get; set; }
        public string otel { get; set; }
        public string username { get; set; }
        public string sms { get; set; }
        public decimal credits { get; set; }
        public decimal bkno { get; set; }
        public decimal blk { get; set; }
        public decimal can { get; set; }
        public decimal mno { get; set; }
        public decimal referral { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal smsacc { get; set; }
        public string statusmsg { get; set; }
        public string smsid { get; set; }
        public decimal smstpl { get; set; }
    }
}
