//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class spider
    {
        public decimal trz { get; set; }
        public System.DateTime trx { get; set; }
        public decimal referral { get; set; }
        public decimal srno { get; set; }
        public decimal mno { get; set; }
        public System.DateTime spdate { get; set; }
        public decimal interval { get; set; }
        public decimal keyw { get; set; }
        public decimal complby { get; set; }
        public string rem1 { get; set; }
        public decimal can { get; set; }
        public decimal sp1 { get; set; }
        public decimal sp2 { get; set; }
        public decimal sp3 { get; set; }
        public decimal sp4 { get; set; }
        public decimal sp5 { get; set; }
        public decimal sp6 { get; set; }
        public decimal sp7 { get; set; }
        public decimal sp8 { get; set; }
        public string user_new { get; set; }
        public System.DateTime user_new_date { get; set; }
        public string user_delete { get; set; }
        public System.DateTime user_delete_date { get; set; }
        public decimal bkno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
