//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class submod
    {
        public decimal TRZ { get; set; }
        public System.DateTime TRX { get; set; }
        public int MNO { get; set; }
        public int REFERRAL { get; set; }
        public int SRNO { get; set; }
        public int TMSRNO { get; set; }
        public System.DateTime SMDATE { get; set; }
        public decimal PHSTBL { get; set; }
        public decimal PHWTH { get; set; }
        public decimal PHMAIN { get; set; }
        public decimal PHRELPR { get; set; }
        public decimal PSYMOTI { get; set; }
        public decimal PSYCNMG { get; set; }
        public decimal PSYFSNI { get; set; }
        public decimal PSYCGBH { get; set; }
        public decimal PSYMNTH { get; set; }
        public decimal PSYDNMC { get; set; }
        public decimal PSYSTP { get; set; }
        public decimal PSYCOUN { get; set; }
        public string PSYOTHR { get; set; }
        public decimal RECPEER { get; set; }
        public decimal RECMAID { get; set; }
        public decimal RECFMSP { get; set; }
        public decimal RECPRNT { get; set; }
        public decimal RECHSE { get; set; }
        public decimal RECEMP { get; set; }
        public decimal RECEDUT { get; set; }
        public decimal RECWPRJ { get; set; }
        public decimal RECCHKP { get; set; }
        public decimal RECRLPP { get; set; }
        public decimal RECCMPT { get; set; }
        public decimal RECGNH { get; set; }
        public string RECOTH { get; set; }
        public decimal CAN { get; set; }
        public string USER_NEW { get; set; }
        public System.DateTime USER_NEW_DATE { get; set; }
        public string USER_DELETE { get; set; }
        public System.DateTime USER_DELETE_DATE { get; set; }
        public decimal KEYW { get; set; }
        public Nullable<decimal> bkno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public int CBIYPS { get; set; }
        public int MIYPS { get; set; }
        public int SFIFTYPS { get; set; }
        public int MCPYPS { get; set; }
        public int CMYPS { get; set; }
        public int CYPS { get; set; }
        public int YPEDTR { get; set; }
        public int YPEVOL { get; set; }
        public int YPINHOU { get; set; }
        public int YPRGFS { get; set; }
        public int YPGPS { get; set; }
        public int YPPSIM { get; set; }
        public int YPMHLTH { get; set; }
        public int YPOFFND { get; set; }
        public int YPHEALTH { get; set; }
        public int YPSHP { get; set; }
        public int YPMATY { get; set; }
        public int YPDISSER { get; set; }
        public int YPBESER { get; set; }
        public int YPYCAR { get; set; }
        public int YPSER { get; set; }
        public int YPCSC { get; set; }
        public decimal APHWITH { get; set; }
        public decimal APHREPR { get; set; }
    }
}
