//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sumrole
    {
        public decimal sumrole1 { get; set; }
        public string name { get; set; }
        public decimal can { get; set; }
        public decimal status { get; set; }
        public string prjgrp { get; set; }
        public string admrole { get; set; }
        public string reprole { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal cst { get; set; }
    }
}
