//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemlog
    {
        public Nullable<decimal> syslogid { get; set; }
        public string sessionid { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public Nullable<System.DateTime> logtime { get; set; }
        public string ipaddress { get; set; }
        public Nullable<int> can { get; set; }
        public Nullable<System.DateTime> logluse { get; set; }
        public Nullable<System.DateTime> logouttime { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public decimal locked { get; set; }
    }
}
