//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class template
    {
        public decimal template1 { get; set; }
        public string name { get; set; }
        public decimal can { get; set; }
        public decimal cst { get; set; }
        public string tablename { get; set; }
        public string pkfield { get; set; }
        public decimal history { get; set; }
        public decimal referral { get; set; }
        public string tabs { get; set; }
        public decimal active { get; set; }
        public decimal usetabs { get; set; }
        public string xmldesign { get; set; }
        public string wcsfilename { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
