//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tops
    {
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int srno { get; set; }
        public int mno { get; set; }
        public int referral { get; set; }
        public Nullable<System.DateTime> topdate { get; set; }
        public Nullable<decimal> trstage { get; set; }
        public Nullable<decimal> alc1 { get; set; }
        public Nullable<decimal> alc2 { get; set; }
        public Nullable<decimal> alc3 { get; set; }
        public Nullable<decimal> alc4 { get; set; }
        public Nullable<decimal> alcav { get; set; }
        public string alctotal { get; set; }
        public Nullable<decimal> opi1 { get; set; }
        public Nullable<decimal> opi2 { get; set; }
        public Nullable<decimal> opi3 { get; set; }
        public Nullable<decimal> opi4 { get; set; }
        public Nullable<decimal> opiav { get; set; }
        public string opitotal { get; set; }
        public Nullable<decimal> cra1 { get; set; }
        public Nullable<decimal> cra2 { get; set; }
        public Nullable<decimal> cra3 { get; set; }
        public Nullable<decimal> cra4 { get; set; }
        public Nullable<decimal> craav { get; set; }
        public string cratotal { get; set; }
        public Nullable<decimal> coc1 { get; set; }
        public Nullable<decimal> coc2 { get; set; }
        public Nullable<decimal> coc3 { get; set; }
        public Nullable<decimal> coc4 { get; set; }
        public Nullable<decimal> cocav { get; set; }
        public string coctotal { get; set; }
        public Nullable<decimal> amp1 { get; set; }
        public Nullable<decimal> amp2 { get; set; }
        public Nullable<decimal> amp3 { get; set; }
        public Nullable<decimal> amp4 { get; set; }
        public Nullable<decimal> ampav { get; set; }
        public string amptotal { get; set; }
        public Nullable<decimal> can1 { get; set; }
        public Nullable<decimal> can2 { get; set; }
        public Nullable<decimal> can3 { get; set; }
        public Nullable<decimal> can4 { get; set; }
        public Nullable<decimal> canav { get; set; }
        public string cantotal { get; set; }
        public Nullable<decimal> otherdrug { get; set; }
        public Nullable<decimal> oth1 { get; set; }
        public Nullable<decimal> oth2 { get; set; }
        public Nullable<decimal> oth3 { get; set; }
        public Nullable<decimal> oth4 { get; set; }
        public Nullable<decimal> othav { get; set; }
        public string othtotal { get; set; }
        public Nullable<decimal> inj1 { get; set; }
        public Nullable<decimal> inj2 { get; set; }
        public Nullable<decimal> inj3 { get; set; }
        public Nullable<decimal> inj4 { get; set; }
        public string injtotal { get; set; }
        public Nullable<decimal> shareneed { get; set; }
        public Nullable<decimal> shareoth { get; set; }
        public string sharetotal { get; set; }
        public Nullable<decimal> slift1 { get; set; }
        public Nullable<decimal> slift2 { get; set; }
        public Nullable<decimal> slift3 { get; set; }
        public Nullable<decimal> slift4 { get; set; }
        public string slifttotal { get; set; }
        public Nullable<decimal> dsell1 { get; set; }
        public Nullable<decimal> dsell2 { get; set; }
        public Nullable<decimal> dsell3 { get; set; }
        public Nullable<decimal> dsell4 { get; set; }
        public string dselltotal { get; set; }
        public Nullable<decimal> vehicle { get; set; }
        public Nullable<decimal> burglary { get; set; }
        public Nullable<decimal> fraud { get; set; }
        public string thefttotal { get; set; }
        public Nullable<decimal> assviol { get; set; }
        public string assvtotal { get; set; }
        public Nullable<decimal> psyhs { get; set; }
        public Nullable<decimal> pwork1 { get; set; }
        public Nullable<decimal> pwork2 { get; set; }
        public Nullable<decimal> pwork3 { get; set; }
        public Nullable<decimal> pwork4 { get; set; }
        public string pworktotal { get; set; }
        public Nullable<decimal> coll1 { get; set; }
        public Nullable<decimal> coll2 { get; set; }
        public Nullable<decimal> coll3 { get; set; }
        public Nullable<decimal> coll4 { get; set; }
        public string colltotal { get; set; }
        public Nullable<decimal> phyhs { get; set; }
        public Nullable<decimal> hproblem { get; set; }
        public Nullable<decimal> riskevict { get; set; }
        public Nullable<decimal> qlife { get; set; }
        public Nullable<decimal> can { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public string phyhstotal { get; set; }
        public string psyhstotal { get; set; }
        public string qlifetotal { get; set; }
        public string hprobtotal { get; set; }
        public string risktotal { get; set; }
        public Nullable<decimal> nonta { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal bkno { get; set; }
        public string consmp { get; set; }
    }
}
