//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tplfield
    {
        public decimal tplfield1 { get; set; }
        public decimal mod_id { get; set; }
        public string name { get; set; }
        public string label { get; set; }
        public Nullable<decimal> type { get; set; }
        public decimal ddtpl { get; set; }
        public decimal defid { get; set; }
        public decimal orderno { get; set; }
        public decimal can { get; set; }
        public decimal digits { get; set; }
        public decimal @decimal { get; set; }
        public decimal chars { get; set; }
        public decimal ddblank { get; set; }
        public decimal islut { get; set; }
        public decimal apponlyta { get; set; }
        public decimal radiorender { get; set; }
        public string xmloptions { get; set; }
        public decimal cst { get; set; }
        public decimal scid { get; set; }
        public decimal @readonly { get; set; }
        public decimal parentmod_old { get; set; }
        public decimal childmod_old { get; set; }
        public decimal ddlink { get; set; }
        public string label_audit { get; set; }
        public decimal taheader { get; set; }
        public decimal tplfield_imp { get; set; }
        public decimal calcfunc { get; set; }
        public string calcfields { get; set; }
        public decimal checkval { get; set; }
        public string guid { get; set; }
        public string parentmod { get; set; }
        public string childmod { get; set; }
        public string ddlut { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<int> minval { get; set; }
        public Nullable<int> maxval { get; set; }
    }
}
