//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tplrule
    {
        public decimal tplrule1 { get; set; }
        public decimal mod_id { get; set; }
        public decimal type { get; set; }
        public decimal tplfield { get; set; }
        public decimal tplfield1 { get; set; }
        public decimal tplfield2 { get; set; }
        public decimal tplfield3 { get; set; }
        public decimal tplfield4 { get; set; }
        public decimal can { get; set; }
        public decimal cst { get; set; }
        public decimal f_left { get; set; }
        public string name { get; set; }
        public string guid { get; set; }
        public string guid1 { get; set; }
        public string guid2 { get; set; }
        public string guid3 { get; set; }
        public string guid4 { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string advrule { get; set; }
        public string advmsg { get; set; }
        public string advexec { get; set; }
    }
}
