//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatime
    {
        public decimal TRZ { get; set; }
        public System.DateTime TRX { get; set; }
        public int MNO { get; set; }
        public int REFERRAL { get; set; }
        public int srno { get; set; }
        public System.DateTime titdate { get; set; }
        public decimal titreat { get; set; }
        public string rem1 { get; set; }
        public decimal CAN { get; set; }
        public string USER_NEW { get; set; }
        public System.DateTime USER_NEW_DATE { get; set; }
        public string USER_DELETE { get; set; }
        public System.DateTime USER_DELETE_DATE { get; set; }
        public Nullable<decimal> bkno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
