//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class treatmod
    {
        public Nullable<decimal> dexp { get; set; }
        public int srno { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int referral { get; set; }
        public int mno { get; set; }
        public Nullable<decimal> type { get; set; }
        public Nullable<System.DateTime> trstart { get; set; }
        public Nullable<System.DateTime> trend { get; set; }
        public Nullable<decimal> troutcome { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public Nullable<decimal> bkno { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public Nullable<System.DateTime> modref { get; set; }
        public Nullable<System.DateTime> firstapp { get; set; }
        public string user_upd { get; set; }
        public Nullable<decimal> trmodexit { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal gprac { get; set; }
        public decimal agcode { get; set; }
        public string remarks { get; set; }
        public string OPRAGNCY { get; set; }
        public decimal modset { get; set; }
    }
}
