//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urine_totest
    {
        public Nullable<decimal> dexp { get; set; }
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int srno { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> urdate { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public Nullable<decimal> type { get; set; }
        public Nullable<decimal> ur1 { get; set; }
        public Nullable<decimal> ur2 { get; set; }
        public Nullable<decimal> ur3 { get; set; }
        public Nullable<decimal> ur4 { get; set; }
        public Nullable<decimal> ur5 { get; set; }
        public Nullable<decimal> ur6 { get; set; }
        public Nullable<decimal> ur7 { get; set; }
        public Nullable<decimal> ur8 { get; set; }
        public string rem1 { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> attended { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public Nullable<decimal> bkno { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public Nullable<decimal> ur9 { get; set; }
        public Nullable<decimal> ur10 { get; set; }
        public Nullable<decimal> ur11 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal disuse { get; set; }
    }
}
