//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usrs_dat
    {
        public decimal user_id { get; set; }
        public string user_name { get; set; }
        public string passkey { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> interval { get; set; }
        public Nullable<System.DateTime> passdate { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public string user_upd { get; set; }
        public string wbusername { get; set; }
        public string wbpassword { get; set; }
        public string namefamily { get; set; }
        public string namegiven { get; set; }
        public string namesecond { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public Nullable<decimal> userctg { get; set; }
        public Nullable<decimal> defschfld { get; set; }
        public Nullable<decimal> defschtype { get; set; }
        public Nullable<System.DateTime> dtchanged { get; set; }
        public Nullable<decimal> authrefuser { get; set; }
        public string ad1 { get; set; }
        public string ad2 { get; set; }
        public string ad3 { get; set; }
        public string ad4 { get; set; }
        public string otel { get; set; }
        public string mobiletel { get; set; }
        public string ertel { get; set; }
        public string emailbox { get; set; }
        public Nullable<decimal> refs { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> ptclaxs { get; set; }
        public Nullable<System.DateTime> dtlastacc { get; set; }
        public Nullable<decimal> pswnoexp { get; set; }
        public Nullable<decimal> autref { get; set; }
        public string prjgrp { get; set; }
        public string admrole { get; set; }
        public string reprole { get; set; }
        public string sumrole { get; set; }
        public string defproj { get; set; }
        public Nullable<decimal> forcedpsw { get; set; }
        public Nullable<int> timeoutsec { get; set; }
        public Nullable<int> expdays { get; set; }
        public Nullable<int> suspdays { get; set; }
        public decimal office { get; set; }
        public Nullable<int> cst { get; set; }
        public string pin { get; set; }
    }
}
