//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp13
    {
        public decimal srno { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public Nullable<decimal> trz { get; set; }
        public int mno { get; set; }
        public int referral { get; set; }
        public decimal can { get; set; }
        public System.DateTime docdate { get; set; }
        public string docuname { get; set; }
        public string doctype { get; set; }
        public string docdescr { get; set; }
        public string rem1 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string docfile { get; set; }
        public string filename { get; set; }
        public string docext { get; set; }
    }
}
