//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp1b
    {
        public int mno { get; set; }
        public string sn { get; set; }
        public string fn { get; set; }
        public string snal { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<decimal> gender { get; set; }
        public string persno { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public Nullable<decimal> jeyw { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<System.DateTime> adate { get; set; }
        public Nullable<decimal> defkeyw { get; set; }
        public Nullable<decimal> flag { get; set; }
        public string delname { get; set; }
        public Nullable<System.DateTime> deldate { get; set; }
        public Nullable<System.DateTime> trandate { get; set; }
        public Nullable<decimal> area { get; set; }
        public Nullable<decimal> region { get; set; }
        public Nullable<decimal> probknown { get; set; }
        public Nullable<decimal> yot { get; set; }
        public Nullable<decimal> ntaconsent { get; set; }
        public Nullable<decimal> gpshare { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public Nullable<decimal> scriptshold { get; set; }
        public Nullable<decimal> ndtms { get; set; }
        public Nullable<decimal> riskass { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public Nullable<decimal> clot { get; set; }
        public Nullable<decimal> ypw { get; set; }
        public Nullable<decimal> bbv { get; set; }
        public Nullable<System.DateTime> accdate { get; set; }
        public string accby { get; set; }
        public string user_upd { get; set; }
        public Nullable<decimal> prjgrp { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string photo { get; set; }
        public Nullable<decimal> hastop { get; set; }
        public Nullable<decimal> whynotop { get; set; }
        public Nullable<decimal> topagency { get; set; }
        public Nullable<decimal> ppo { get; set; }
        public decimal smsremind { get; set; }
    }
}
