//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp1p
    {
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int mnop { get; set; }
        public string sn { get; set; }
        public string fn { get; set; }
        public Nullable<decimal> gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string ad1 { get; set; }
        public string ad2 { get; set; }
        public string ad3 { get; set; }
        public string ad4 { get; set; }
        public string ad5 { get; set; }
        public Nullable<decimal> ad6 { get; set; }
        public string ad7 { get; set; }
        public string htel { get; set; }
        public string otel { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> refd { get; set; }
        public Nullable<decimal> refs { get; set; }
        public Nullable<decimal> assroute { get; set; }
        public string rem1 { get; set; }
        public string rem2 { get; set; }
        public Nullable<decimal> status { get; set; }
        public Nullable<System.DateTime> assdate { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> prjgrp { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public decimal invp1 { get; set; }
        public string transby { get; set; }
        public System.DateTime transdate { get; set; }
        public decimal cst { get; set; }
        public decimal keyw { get; set; }
        public decimal htelr { get; set; }
        public decimal htelm { get; set; }
        public decimal htelw { get; set; }
        public decimal hemailr { get; set; }
        public decimal otelr { get; set; }
        public decimal otelm { get; set; }
        public decimal district { get; set; }
        public decimal office { get; set; }
    }
}
