//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp20
    {
        public decimal srno { get; set; }
        public Nullable<System.DateTime> helpdate { get; set; }
        public string initials { get; set; }
        public string reference { get; set; }
        public string tfrom { get; set; }
        public string tto { get; set; }
        public Nullable<decimal> duration { get; set; }
        public Nullable<decimal> nature { get; set; }
        public Nullable<decimal> initype { get; set; }
        public Nullable<decimal> calbef { get; set; }
        public Nullable<decimal> heardc { get; set; }
        public Nullable<decimal> heardu { get; set; }
        public Nullable<decimal> genderc { get; set; }
        public Nullable<decimal> genderu { get; set; }
        public Nullable<decimal> relat { get; set; }
        public string relatx { get; set; }
        public Nullable<decimal> ethnicc { get; set; }
        public Nullable<decimal> ethnicu { get; set; }
        public Nullable<decimal> agec { get; set; }
        public Nullable<decimal> ageu { get; set; }
        public Nullable<decimal> drugct { get; set; }
        public Nullable<decimal> drug1 { get; set; }
        public Nullable<decimal> drug2 { get; set; }
        public Nullable<decimal> drug3 { get; set; }
        public Nullable<decimal> drug4 { get; set; }
        public Nullable<decimal> drug5 { get; set; }
        public string drugx { get; set; }
        public Nullable<decimal> ild1 { get; set; }
        public Nullable<decimal> ild2 { get; set; }
        public Nullable<decimal> ild3 { get; set; }
        public Nullable<decimal> ild4 { get; set; }
        public Nullable<decimal> ild5 { get; set; }
        public Nullable<decimal> ild6 { get; set; }
        public Nullable<decimal> ild7 { get; set; }
        public Nullable<decimal> ild8 { get; set; }
        public Nullable<decimal> ild9 { get; set; }
        public string ildx { get; set; }
        public Nullable<decimal> resp { get; set; }
        public string respx { get; set; }
        public string respmem1 { get; set; }
        public string agencyinfo { get; set; }
        public string helpname { get; set; }
        public string ad1 { get; set; }
        public string ad2 { get; set; }
        public string ad3 { get; set; }
        public string ad4 { get; set; }
        public string ad5 { get; set; }
        public Nullable<decimal> ad6 { get; set; }
        public string ad7 { get; set; }
        public string htel { get; set; }
        public Nullable<decimal> pctc { get; set; }
        public Nullable<decimal> pctu { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> illdrug1 { get; set; }
        public Nullable<decimal> illdrug2 { get; set; }
        public Nullable<decimal> illdrug3 { get; set; }
        public Nullable<decimal> illdrug4 { get; set; }
        public decimal cst { get; set; }
    }
}
