//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp5
    {
        public int srno { get; set; }
        public int mno { get; set; }
        public string name { get; set; }
        public decimal age { get; set; }
        public decimal gender { get; set; }
        public decimal live { get; set; }
        public decimal probage { get; set; }
        public decimal curelat { get; set; }
        public decimal ethnic { get; set; }
        public decimal pregnant { get; set; }
        public string rem1 { get; set; }
        public decimal can { get; set; }
        public decimal trz { get; set; }
        public System.DateTime trx { get; set; }
        public decimal dext { get; set; }
        public decimal dexp { get; set; }
        public decimal dexp1 { get; set; }
        public decimal trj { get; set; }
        public decimal referral { get; set; }
        public decimal clcat { get; set; }
        public decimal evseen { get; set; }
        public System.DateTime evseendate { get; set; }
        public decimal prot1 { get; set; }
        public decimal prot2 { get; set; }
        public decimal prot3 { get; set; }
        public decimal prot4 { get; set; }
        public System.DateTime prot4d { get; set; }
        public decimal thsent { get; set; }
        public string protdis { get; set; }
        public decimal chpiss { get; set; }
        public decimal chpyes { get; set; }
        public decimal domvol { get; set; }
        public string chprotect { get; set; }
        public decimal childh { get; set; }
        public decimal childi { get; set; }
        public decimal childe { get; set; }
        public decimal parstat { get; set; }
        public decimal parresp { get; set; }
        public System.DateTime prot1ad { get; set; }
        public System.DateTime prot2ad { get; set; }
        public System.DateTime prot3ad { get; set; }
        public System.DateTime prot1d { get; set; }
        public System.DateTime prot2d { get; set; }
        public System.DateTime prot3d { get; set; }
        public string domvrem { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
