//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp50cp
    {
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int vp50cpID { get; set; }
        public Nullable<int> mno { get; set; }
        public Nullable<int> srno { get; set; }
        public Nullable<decimal> cp1 { get; set; }
        public Nullable<decimal> cp2 { get; set; }
        public Nullable<decimal> cp3 { get; set; }
        public Nullable<decimal> cp4 { get; set; }
        public Nullable<decimal> cp5 { get; set; }
        public Nullable<decimal> cp6 { get; set; }
        public Nullable<decimal> cp7 { get; set; }
        public Nullable<decimal> cp8 { get; set; }
        public Nullable<decimal> cp9 { get; set; }
        public Nullable<decimal> cp10 { get; set; }
        public Nullable<decimal> cp11 { get; set; }
        public Nullable<decimal> cp12 { get; set; }
        public Nullable<decimal> cp13 { get; set; }
        public Nullable<decimal> cp14 { get; set; }
        public Nullable<decimal> cp15 { get; set; }
        public Nullable<decimal> cp16 { get; set; }
        public Nullable<decimal> cp17 { get; set; }
        public Nullable<decimal> cp18 { get; set; }
        public Nullable<decimal> cp19 { get; set; }
        public Nullable<System.DateTime> cp1date { get; set; }
        public Nullable<System.DateTime> cp2date { get; set; }
        public Nullable<System.DateTime> cp3date { get; set; }
        public Nullable<System.DateTime> cp4date { get; set; }
        public Nullable<System.DateTime> cp5date { get; set; }
        public Nullable<System.DateTime> cp6date { get; set; }
        public Nullable<System.DateTime> cp7date { get; set; }
        public Nullable<System.DateTime> cp8date { get; set; }
        public Nullable<System.DateTime> cp9date { get; set; }
        public Nullable<System.DateTime> cp10date { get; set; }
        public Nullable<System.DateTime> cp11date { get; set; }
        public Nullable<System.DateTime> cp12date { get; set; }
        public Nullable<System.DateTime> cp13date { get; set; }
        public Nullable<System.DateTime> cp14date { get; set; }
        public Nullable<System.DateTime> cp15date { get; set; }
        public Nullable<System.DateTime> cp16date { get; set; }
        public Nullable<System.DateTime> cp17date { get; set; }
        public Nullable<System.DateTime> cp18date { get; set; }
        public Nullable<System.DateTime> cp19date { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
