//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp50accom
    {
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public decimal arno { get; set; }
        public Nullable<decimal> srno { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> curreside { get; set; }
        public Nullable<decimal> accaccom { get; set; }
        public Nullable<decimal> accarr { get; set; }
        public Nullable<decimal> nfatype { get; set; }
        public Nullable<decimal> temptype { get; set; }
        public Nullable<decimal> settype { get; set; }
        public string nfatypeo { get; set; }
        public string temptypeo { get; set; }
        public string settypeo { get; set; }
        public Nullable<decimal> livewcom { get; set; }
        public string livewcomo { get; set; }
        public Nullable<decimal> retaccom { get; set; }
        public Nullable<decimal> hissue { get; set; }
        public string hissuerem { get; set; }
        public string homerem { get; set; }
        public Nullable<decimal> finissue { get; set; }
        public string finisrem { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> vp50accomID { get; set; }
        public string parrem { get; set; }
    }
}
