//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp50ra
    {
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int mno { get; set; }
        public int srno { get; set; }
        public Nullable<decimal> datra { get; set; }
        public Nullable<decimal> ratype { get; set; }
        public Nullable<System.DateTime> radate { get; set; }
        public Nullable<decimal> attinit { get; set; }
        public Nullable<decimal> attfol { get; set; }
        public Nullable<decimal> attinityes { get; set; }
        public Nullable<decimal> attfolyes { get; set; }
        public Nullable<decimal> attinitno { get; set; }
        public Nullable<decimal> attfolno { get; set; }
        public string attinityeso { get; set; }
        public string attinitnoo { get; set; }
        public string attfolyeso { get; set; }
        public string attfolnoo { get; set; }
        public Nullable<decimal> polinit { get; set; }
        public Nullable<decimal> polfol { get; set; }
        public Nullable<decimal> setinra { get; set; }
        public Nullable<decimal> setinrano { get; set; }
        public string setinranoo { get; set; }
        public Nullable<decimal> inleadtr { get; set; }
        public Nullable<decimal> inleadcp { get; set; }
        public Nullable<decimal> inleadnone { get; set; }
        public Nullable<decimal> inleadno { get; set; }
        public string inleadnoo { get; set; }
        public Nullable<decimal> foleadnone { get; set; }
        public Nullable<decimal> foleadcp { get; set; }
        public Nullable<decimal> foleadtr { get; set; }
        public Nullable<decimal> foleadno { get; set; }
        public string foleadnoo { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> formname { get; set; }
        public string formtel { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal inlead { get; set; }
        public decimal folead { get; set; }
        public string formemail { get; set; }
        public string formcode { get; set; }
        public System.DateTime dtdate { get; set; }
        public string racustody { get; set; }
        public Nullable<int> CMS_ID { get; set; }
        public System.DateTime compdate1 { get; set; }
        public string datcode { get; set; }
        public int noxml { get; set; }
    }
}
