//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp50ic
    {
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public Nullable<decimal> mno { get; set; }
        public Nullable<decimal> formname { get; set; }
        public string formtel { get; set; }
        public string formdat { get; set; }
        public Nullable<System.DateTime> datecont { get; set; }
        public Nullable<decimal> datmade { get; set; }
        public Nullable<decimal> noscreen { get; set; }
        public string noscreeno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal vp50icID { get; set; }
    }
}
