//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp50cont
    {
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int crno { get; set; }
        public Nullable<int> srno { get; set; }
        public Nullable<int> mno { get; set; }
        public Nullable<decimal> formname2 { get; set; }
        public Nullable<decimal> scalla { get; set; }
        public Nullable<decimal> sc1a { get; set; }
        public Nullable<decimal> sc2a { get; set; }
        public Nullable<decimal> sc3a { get; set; }
        public Nullable<decimal> sc4a { get; set; }
        public Nullable<decimal> sc5a { get; set; }
        public Nullable<decimal> sc6a { get; set; }
        public Nullable<decimal> sc7a { get; set; }
        public Nullable<decimal> sc8a { get; set; }
        public Nullable<decimal> sc9a { get; set; }
        public string datprname1 { get; set; }
        public Nullable<System.DateTime> compdate1 { get; set; }
        public string formtel2 { get; set; }
        public Nullable<decimal> scallb { get; set; }
        public Nullable<decimal> sc1b { get; set; }
        public Nullable<decimal> sc2b { get; set; }
        public Nullable<decimal> sc3b { get; set; }
        public Nullable<decimal> sc4b { get; set; }
        public Nullable<decimal> sc5b { get; set; }
        public Nullable<decimal> sc6b { get; set; }
        public Nullable<decimal> sc7b { get; set; }
        public Nullable<decimal> sc8b { get; set; }
        public Nullable<decimal> sc9b { get; set; }
        public string datprname2 { get; set; }
        public Nullable<System.DateTime> compdate2 { get; set; }
        public string dsname1 { get; set; }
        public string dsname2 { get; set; }
        public string dsorg1 { get; set; }
        public string dsorg2 { get; set; }
        public string dsphone1 { get; set; }
        public string dsphone2 { get; set; }
        public Nullable<System.DateTime> dsdate1 { get; set; }
        public Nullable<System.DateTime> dsdate2 { get; set; }
        public string imatt { get; set; }
        public string clback { get; set; }
        public string hissues { get; set; }
        public Nullable<decimal> contkeyw { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string mflong { get; set; }
        public decimal icintp { get; set; }
        public decimal icintp2 { get; set; }
        public decimal nsti { get; set; }
        public string nstio { get; set; }
        public decimal dmis2 { get; set; }
        public decimal dmis3 { get; set; }
        public decimal drugadm { get; set; }
        public string drugadmo { get; set; }
        public string rem1 { get; set; }
        public decimal refdatin { get; set; }
        public decimal prisonin { get; set; }
        public decimal noscreen { get; set; }
        public string noscreeno { get; set; }
        public string email { get; set; }
        public decimal alcfreq { get; set; }
        public string formcode { get; set; }
        public decimal odrug1 { get; set; }
        public decimal odrug2 { get; set; }
        public decimal nodrug { get; set; }
        public Nullable<int> dipstatus { get; set; }
    }
}
