//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp50act
    {
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int actno { get; set; }
        public int srno { get; set; }
        public int mno { get; set; }
        public Nullable<int> bkno { get; set; }
        public System.DateTime p2d { get; set; }
        public decimal newprov1 { get; set; }
        public string newprov1o { get; set; }
        public System.DateTime newagdate1 { get; set; }
        public decimal newprov2 { get; set; }
        public string newprov2o { get; set; }
        public System.DateTime newagdate2 { get; set; }
        public System.DateTime harmdate { get; set; }
        public System.DateTime overmdate { get; set; }
        public System.DateTime rapidpdate { get; set; }
        public System.DateTime gwdate { get; set; }
        public System.DateTime crackdate { get; set; }
        public System.DateTime strucdate { get; set; }
        public System.DateTime bialcdate { get; set; }
        public System.DateTime primhdate { get; set; }
        public System.DateTime fadvdate { get; set; }
        public System.DateTime comhdate { get; set; }
        public System.DateTime hadvdate { get; set; }
        public System.DateTime peersdate { get; set; }
        public System.DateTime leisdate { get; set; }
        public System.DateTime supedudate { get; set; }
        public System.DateTime fsupdate { get; set; }
        public System.DateTime supempdate { get; set; }
        public System.DateTime osupdate { get; set; }
        public string osuptext { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public string rem1 { get; set; }
        public decimal can { get; set; }
        public Nullable<int> CMS_ID { get; set; }
    }
}
