//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp51
    {
        public decimal srno { get; set; }
        public decimal suspno { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> vp50s { get; set; }
        public string vp50so { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<System.DateTime> reengage { get; set; }
        public Nullable<decimal> vp50supr { get; set; }
        public Nullable<decimal> dexp { get; set; }
        public Nullable<decimal> dexp1 { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
