//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp6
    {
        public int srno { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> added { get; set; }
        public string childname { get; set; }
        public string mother { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> doe { get; set; }
        public Nullable<System.DateTime> dod { get; set; }
        public string nok { get; set; }
        public string lastad { get; set; }
        public string forwad { get; set; }
        public Nullable<decimal> pno { get; set; }
        public Nullable<decimal> school { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public string socnam { get; set; }
        public string socad { get; set; }
        public string soctel { get; set; }
        public string socemtel { get; set; }
        public string guardian { get; set; }
        public string guardtel { get; set; }
        public string guardad { get; set; }
        public Nullable<decimal> guardcon { get; set; }
        public Nullable<decimal> flang { get; set; }
        public Nullable<decimal> ethnic { get; set; }
        public Nullable<decimal> religion { get; set; }
        public string childprot { get; set; }
        public Nullable<decimal> can { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public decimal gender { get; set; }
    }
}
