//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp6p
    {
        public int vp6pid { get; set; }
        public int srno { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> vp6pdate { get; set; }
        public string rem1 { get; set; }
        public string rem2 { get; set; }
        public string rem3 { get; set; }
        public string rem4 { get; set; }
        public string rem5 { get; set; }
        public string rem6 { get; set; }
        public string rem7 { get; set; }
        public Nullable<decimal> can { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
