//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp8
    {
        public decimal srno { get; set; }
        public System.DateTime gwdate { get; set; }
        public decimal gwloc { get; set; }
        public decimal gwtype { get; set; }
        public string groupname { get; set; }
        public Nullable<decimal> can { get; set; }
        public string rem1 { get; set; }
        public string user_new { get; set; }
        public Nullable<System.DateTime> user_new_date { get; set; }
        public string user_delete { get; set; }
        public Nullable<System.DateTime> user_delete_date { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
        public decimal cst { get; set; }
        public string tfrom { get; set; }
        public string tto { get; set; }
        public decimal duration { get; set; }
        public string volunteer { get; set; }
        public string guestsp { get; set; }
        public decimal totalatt { get; set; }
        public string venue { get; set; }
        public decimal actguest { get; set; }
        public decimal actpeer { get; set; }
        public decimal actpsycho { get; set; }
        public decimal acttherapy { get; set; }
        public decimal actother { get; set; }
        public decimal actothername { get; set; }
        public decimal keyw { get; set; }
    }
}
