//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vp99
    {
        public Nullable<decimal> VP9ID { get; set; }
        public decimal MNO { get; set; }
        public decimal REFERRAL { get; set; }
        public System.DateTime DATE { get; set; }
        public decimal ANSW1 { get; set; }
        public decimal ANSW2 { get; set; }
        public decimal ANSW3 { get; set; }
        public decimal ANSW4 { get; set; }
        public decimal ANSW5 { get; set; }
        public decimal ANSW6 { get; set; }
        public decimal ANSW7 { get; set; }
        public decimal ANSW8 { get; set; }
        public decimal ANSW9 { get; set; }
        public decimal ANSW10 { get; set; }
        public decimal ANSW11 { get; set; }
        public decimal ANSW12 { get; set; }
        public decimal CAN { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
