//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AZHepHiv
    {
        public string serno { get; set; }
        public string name { get; set; }
        public string persno { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string hepstat { get; set; }
        public string hepbtot { get; set; }
        public string prevhepb { get; set; }
        public string refhepgt { get; set; }
        public string hepcistat { get; set; }
        public string hepctd { get; set; }
        public string hepcstat { get; set; }
        public Nullable<System.DateTime> hepcdate { get; set; }
        public string hiv { get; set; }
        public string hivr { get; set; }
        public System.DateTime hivdate { get; set; }
        public string bbv { get; set; }
        public int mno { get; set; }
        public int referral { get; set; }
        public string nhsno { get; set; }
    }
}
