//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AZReferralOn
    {
        public string sn { get; set; }
        public string fn { get; set; }
        public string persno { get; set; }
        public string nhsno { get; set; }
        public Nullable<decimal> prjgrp { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> refdate { get; set; }
        public Nullable<int> provider { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<decimal> accepted { get; set; }
        public Nullable<System.DateTime> withdrawn { get; set; }
        public Nullable<System.DateTime> admitted { get; set; }
        public Nullable<System.DateTime> discharge { get; set; }
    }
}
