//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AZStandard
    {
        public string serno { get; set; }
        public string purname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> rdate { get; set; }
        public Nullable<int> rtotal { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<int> etotal { get; set; }
        public string ppri { get; set; }
        public string keyw { get; set; }
        public string outcome { get; set; }
        public string clcat { get; set; }
        public string persno { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> review { get; set; }
        public string edays { get; set; }
        public string prjgrp { get; set; }
        public string doctor { get; set; }
        public string pcg { get; set; }
        public string gprac { get; set; }
        public int referral { get; set; }
    }
}
