//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AZEventsStat
    {
        public int mno { get; set; }
        public decimal referral { get; set; }
        public decimal etype { get; set; }
        public decimal estatus { get; set; }
        public Nullable<System.DateTime> evdate { get; set; }
        public int bkno { get; set; }
        public Nullable<decimal> duration { get; set; }
        public decimal evloc { get; set; }
        public decimal keyw { get; set; }
    }
}
