//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DIP5
    {
        public int mno { get; set; }
        public Nullable<int> vp50 { get; set; }
        public Nullable<int> vp50ra { get; set; }
        public Nullable<int> vp50act { get; set; }
    }
}
