//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_LatestAddresses
    {
        public int mno { get; set; }
        public Nullable<decimal> pct { get; set; }
        public Nullable<decimal> dat { get; set; }
        public Nullable<decimal> ad6 { get; set; }
        public string ad7 { get; set; }
        public int vp4id { get; set; }
        public Nullable<decimal> can { get; set; }
        public Nullable<decimal> district { get; set; }
        public string htel { get; set; }
        public string otel { get; set; }
        public string address { get; set; }
    }
}
