//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zrepm29
    {
        public int mno { get; set; }
        public int referral { get; set; }
        public string sn { get; set; }
        public string fn { get; set; }
        public string persno { get; set; }
        public Nullable<decimal> gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<decimal> prjgrp { get; set; }
        public string nhsno { get; set; }
        public Nullable<System.DateTime> psd { get; set; }
        public Nullable<System.DateTime> pse { get; set; }
        public Nullable<decimal> scdrug { get; set; }
        public Nullable<decimal> dose { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> days { get; set; }
        public Nullable<System.DateTime> printed { get; set; }
        public Nullable<decimal> rm2 { get; set; }
        public Nullable<decimal> chemist { get; set; }
        public Nullable<decimal> signat { get; set; }
        public int scriptno { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public Nullable<System.DateTime> sdue { get; set; }
    }
}
