//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zrepm7
    {
        public int mno { get; set; }
        public int referral { get; set; }
        public Nullable<decimal> type { get; set; }
        public Nullable<decimal> status { get; set; }
        public Nullable<decimal> prison { get; set; }
        public Nullable<System.DateTime> edr { get; set; }
        public string sentence { get; set; }
        public Nullable<System.DateTime> remand { get; set; }
    }
}
