//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zrepm39_1
    {
        public int mno { get; set; }
        public int referral { get; set; }
        public Nullable<System.DateTime> refd { get; set; }
        public Nullable<decimal> gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<decimal> ethnic { get; set; }
        public Nullable<decimal> rf1 { get; set; }
        public Nullable<decimal> rf2 { get; set; }
        public Nullable<decimal> rf3 { get; set; }
        public Nullable<decimal> rf4 { get; set; }
    }
}
