//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zrepm277
    {
        public string sn { get; set; }
        public string fn { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<decimal> gender { get; set; }
        public string persno { get; set; }
        public Nullable<decimal> prjgrp { get; set; }
        public int srno { get; set; }
        public int mno { get; set; }
        public Nullable<System.DateTime> nxdate { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public Nullable<decimal> ad6 { get; set; }
        public string ad7 { get; set; }
        public Nullable<decimal> bkno { get; set; }
        public Nullable<decimal> js1 { get; set; }
        public Nullable<decimal> js2 { get; set; }
        public Nullable<decimal> js3 { get; set; }
        public Nullable<decimal> js4 { get; set; }
        public Nullable<decimal> js5 { get; set; }
        public Nullable<decimal> js6 { get; set; }
        public Nullable<decimal> js7 { get; set; }
        public Nullable<decimal> js8 { get; set; }
        public Nullable<decimal> js9 { get; set; }
        public Nullable<decimal> js10 { get; set; }
        public Nullable<decimal> js11 { get; set; }
        public Nullable<decimal> js12 { get; set; }
        public Nullable<decimal> js13 { get; set; }
        public Nullable<decimal> jb1 { get; set; }
        public Nullable<decimal> jb2 { get; set; }
        public Nullable<decimal> jb3 { get; set; }
        public Nullable<decimal> jb4 { get; set; }
        public Nullable<decimal> jb5 { get; set; }
        public Nullable<decimal> jr1 { get; set; }
        public Nullable<decimal> jr2 { get; set; }
        public Nullable<decimal> jr3 { get; set; }
        public Nullable<decimal> jr4 { get; set; }
        public Nullable<decimal> jr5 { get; set; }
        public Nullable<decimal> evloc { get; set; }
        public Nullable<decimal> jo1 { get; set; }
        public Nullable<decimal> jo2 { get; set; }
        public Nullable<decimal> jo3 { get; set; }
        public Nullable<decimal> jo4 { get; set; }
        public Nullable<decimal> jo5 { get; set; }
        public Nullable<decimal> jo6 { get; set; }
        public Nullable<decimal> jo7 { get; set; }
        public Nullable<decimal> jo8 { get; set; }
        public Nullable<decimal> jo9 { get; set; }
        public Nullable<int> drug { get; set; }
        public Nullable<decimal> ethnic { get; set; }
    }
}
