//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zrepm603
    {
        public int mno { get; set; }
        public int referral { get; set; }
        public Nullable<System.DateTime> refd { get; set; }
        public Nullable<System.DateTime> closed { get; set; }
        public Nullable<decimal> office { get; set; }
        public decimal PBRCLNT { get; set; }
        public Nullable<decimal> clcat { get; set; }
        public Nullable<decimal> accmneed { get; set; }
        public decimal CPLXAS { get; set; }
        public string ndtms { get; set; }
        public Nullable<System.DateTime> triagedate { get; set; }
    }
}
