//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zrepm79
    {
        public int mno { get; set; }
        public Nullable<decimal> scdrug { get; set; }
        public Nullable<decimal> chemist { get; set; }
        public Nullable<decimal> signat { get; set; }
        public Nullable<decimal> rm2 { get; set; }
        public int scriptno { get; set; }
        public Nullable<decimal> prjgrp { get; set; }
    }
}
