//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zrepm491
    {
        public string sn { get; set; }
        public string fn { get; set; }
        public string persno { get; set; }
        public int mno { get; set; }
        public int referral { get; set; }
        public int srno { get; set; }
        public Nullable<System.DateTime> trstart { get; set; }
        public Nullable<System.DateTime> trend { get; set; }
        public Nullable<decimal> type { get; set; }
        public Nullable<decimal> troutcome { get; set; }
        public Nullable<System.DateTime> modref { get; set; }
        public Nullable<System.DateTime> firstapp { get; set; }
        public Nullable<decimal> trmodexit { get; set; }
        public Nullable<decimal> keyw { get; set; }
    }
}
