//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zrepm567c
    {
        public int srno { get; set; }
        public int mno { get; set; }
        public int referral { get; set; }
        public Nullable<System.DateTime> topdate { get; set; }
        public Nullable<decimal> trstage { get; set; }
        public Nullable<decimal> keyw { get; set; }
    }
}
