//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zrepm19
    {
        public Nullable<System.DateTime> evdate { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public Nullable<decimal> evloc { get; set; }
        public Nullable<decimal> etype { get; set; }
        public Nullable<decimal> estatus { get; set; }
        public string tfrom { get; set; }
        public string tto { get; set; }
        public Nullable<int> mno { get; set; }
        public Nullable<decimal> referral { get; set; }
        public string sn { get; set; }
        public string fn { get; set; }
        public string persno { get; set; }
        public System.DateTime senddate { get; set; }
        public string otel { get; set; }
        public string sms { get; set; }
        public string username { get; set; }
    }
}
