//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_zrepm375a12
    {
        public int mno { get; set; }
        public int referral { get; set; }
        public string sn { get; set; }
        public string fn { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string persno { get; set; }
        public string nhsno { get; set; }
        public Nullable<decimal> keyw { get; set; }
        public Nullable<decimal> office { get; set; }
        public Nullable<System.DateTime> refd { get; set; }
        public Nullable<decimal> outcome { get; set; }
        public Nullable<System.DateTime> topdue { get; set; }
        public Nullable<System.DateTime> topstart { get; set; }
        public Nullable<System.DateTime> topend { get; set; }
        public Nullable<System.DateTime> tmstart { get; set; }
        public string htel { get; set; }
        public string otel { get; set; }
    }
}
