//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCJITValidated
    {
        public int cjitid { get; set; }
        public string DatasetStatus { get; set; }
        public Nullable<int> TotalCritical { get; set; }
        public Nullable<int> TotalWarnings { get; set; }
        public string Critical { get; set; }
        public string Warnings { get; set; }
        public string FINITIAL { get; set; }
        public string SINITIAL { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string SEX { get; set; }
        public string Sex_Desc { get; set; }
        public string NATION { get; set; }
        public string ETHNIC { get; set; }
        public Nullable<System.DateTime> REFLD { get; set; }
        public string AGNCY { get; set; }
        public string PC { get; set; }
        public string DATofResidenceCode { get; set; }
        public string DATofResidence_Desc { get; set; }
        public string DAT { get; set; }
        public string ACCMNEED { get; set; }
        public string PREGNANT { get; set; }
        public Nullable<int> YPABACF { get; set; }
        public Nullable<int> YPESTI { get; set; }
        public string PRISON { get; set; }
        public string C_EXITDEST { get; set; }
        public string RFLS { get; set; }
        public Nullable<System.DateTime> TRIAGED { get; set; }
        public string EMPSTAT { get; set; }
        public string DRUG1 { get; set; }
        public string DRUG2 { get; set; }
        public string DRUG3 { get; set; }
        public string ROUTE { get; set; }
        public string INJSTAT { get; set; }
        public Nullable<int> ALCDDAYS { get; set; }
        public Nullable<decimal> ALCUNITS { get; set; }
        public Nullable<System.DateTime> CPLANDT { get; set; }
        public Nullable<System.DateTime> DISD { get; set; }
        public string DISRSN { get; set; }
        public string CLIENT { get; set; }
        public Nullable<int> CLIENTID { get; set; }
        public int EPISODID { get; set; }
        public string CONSENT { get; set; }
        public string PREVTR { get; set; }
        public string YPLCS { get; set; }
        public string PRNTSTAT { get; set; }
        public string AACLWY { get; set; }
        public string YPSSEXEX { get; set; }
        public string YPSLEAD { get; set; }
        public string YPIMHP { get; set; }
        public string YPSSLFHM { get; set; }
        public string YPSESTAT { get; set; }
        public string YPSGP { get; set; }
        public string YPSCAF { get; set; }
        public string YPSUSS { get; set; }
        public string YPSCCH { get; set; }
        public string YPCPL { get; set; }
        public string YPASMFM { get; set; }
        public string YPCSNSM { get; set; }
        public string YPEBABDA { get; set; }
        public string PCT { get; set; }
        public string LA { get; set; }
        public string GPPTCE { get; set; }
        public string DRUG1AGE { get; set; }
        public string CHILDWTH { get; set; }
        public string DUALDIAG { get; set; }
        public string HEPCTSTD { get; set; }
        public string HEPCSTAT { get; set; }
        public string HEPCTD { get; set; }
        public string HEPBVAC { get; set; }
        public string HEPBSTAT { get; set; }
        public string HLCASSDT { get; set; }
        public string TOPCC { get; set; }
        public string YPECAREP { get; set; }
        public string INTRCPTD { get; set; }
        public string RECPDT { get; set; }
        public string EXITD { get; set; }
        public string EXITRSN { get; set; }
        public string RTOAGNCY { get; set; }
        public string PRERREVD { get; set; }
        public string PBRCLNT { get; set; }
        public string CPLXAS { get; set; }
        public string MODAL { get; set; }
        public string REFMODDT { get; set; }
        public string MODSET { get; set; }
        public string MODID { get; set; }
        public string FAOMODDT { get; set; }
        public string MODST { get; set; }
        public string MODEND { get; set; }
        public string MODEXIT { get; set; }
    }
}
