//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCJITClient
    {
        public string CLIENT { get; set; }
        public int CLIENTID { get; set; }
        public string Forename { get; set; }
        public string FINITIAL { get; set; }
        public string Surname { get; set; }
        public string SINITIAL { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string SEX { get; set; }
        public Nullable<decimal> SexCode { get; set; }
        public string Sex_Desc { get; set; }
        public Nullable<decimal> NationalityCode { get; set; }
        public string Nationality_Desc { get; set; }
        public string NATION { get; set; }
        public Nullable<decimal> EthnicGroupCode { get; set; }
        public string EthnicGroup_Desc { get; set; }
        public string ETHNIC { get; set; }
        public string PC { get; set; }
        public Nullable<decimal> DATofResidenceCode { get; set; }
        public string DATofResidence_Desc { get; set; }
        public string DAT { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string AmendedUser { get; set; }
        public Nullable<System.DateTime> AmendedDate { get; set; }
        public Nullable<decimal> RecordDeleted { get; set; }
        public string DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
