//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCJITIntervention
    {
        public int cjitid { get; set; }
        public Nullable<System.DateTime> SUBMODDT { get; set; }
        public int SUBMID { get; set; }
        public string RECPEER { get; set; }
        public string RECMAID { get; set; }
        public string RECFMSP { get; set; }
        public string RECPRNT { get; set; }
        public string RECHSE { get; set; }
        public string RECEMP { get; set; }
        public string RECEDUT { get; set; }
        public string RECWPRJ { get; set; }
        public string RECCHKP { get; set; }
        public string RECRLPP { get; set; }
        public string RECCMPT { get; set; }
        public string RECGNH { get; set; }
        public string RECOTH { get; set; }
        public string PHSTBL { get; set; }
        public string PHWTH { get; set; }
        public string PHMAIN { get; set; }
        public string PHRELPR { get; set; }
        public string APHWITH { get; set; }
        public string APHREPR { get; set; }
        public string PSYMOTI { get; set; }
        public string PSYCNMG { get; set; }
        public string PSYFSNI { get; set; }
        public string PSYCGBH { get; set; }
        public string PSYMNTH { get; set; }
        public string PSYDNMC { get; set; }
        public string PSYSTP { get; set; }
        public string PSYCOUN { get; set; }
        public string PSYOTHR { get; set; }
        public string CBIYPS { get; set; }
        public string MIYPS { get; set; }
        public string SFIFTYPS { get; set; }
        public string MCPYPS { get; set; }
        public string CMYPS { get; set; }
        public string CYPS { get; set; }
        public string YPEDTR { get; set; }
        public string YPEVOL { get; set; }
        public string YPINHOU { get; set; }
        public string YPRGFS { get; set; }
        public string YPGPS { get; set; }
        public string YPPSIM { get; set; }
        public string YPMHLTH { get; set; }
        public string YPOFFND { get; set; }
        public string YPHEALTH { get; set; }
        public string YPSHP { get; set; }
        public string YPMATY { get; set; }
        public string YPDISSER { get; set; }
        public string YPBESER { get; set; }
        public string YPYCAR { get; set; }
        public string YPSER { get; set; }
        public string YPCSC { get; set; }
    }
}
