//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ypor
    {
        public Nullable<decimal> trz { get; set; }
        public Nullable<System.DateTime> trx { get; set; }
        public int srno { get; set; }
        public Nullable<int> mno { get; set; }
        public Nullable<int> referral { get; set; }
        public Nullable<System.DateTime> topdate { get; set; }
        public Nullable<decimal> trstage { get; set; }
        public int keyw { get; set; }
        public decimal can { get; set; }
        public string CANNUSE { get; set; }
        public string ALCUSE { get; set; }
        public string TOANIC { get; set; }
        public string OPIUSE { get; set; }
        public string CRAUSE { get; set; }
        public string COCAUSE { get; set; }
        public string ECSTSYYP { get; set; }
        public string AMPHUSE { get; set; }
        public string SOLVYP { get; set; }
        public string KETAMNYP { get; set; }
        public string GHBYP { get; set; }
        public string LEHIGSYP { get; set; }
        public string TRANYP { get; set; }
        public string OTDRGUSE { get; set; }
        public string OTHR2YP { get; set; }
        public string OTHR3YP { get; set; }
        public string CAUSPD { get; set; }
        public string CONSMP { get; set; }
        public string AAUSFWK { get; set; }
        public string LINSTUS { get; set; }
        public string IVDRGUSE { get; set; }
        public string PTEDAWDD { get; set; }
        public string PTEDAWDE { get; set; }
        public string PTEDAWED { get; set; }
        public string PTEDAWEE { get; set; }
        public string PTEDOYO { get; set; }
        public string PTEUSWDD { get; set; }
        public string PTEUSWDE { get; set; }
        public string PTEUSWED { get; set; }
        public string PTEUSWEE { get; set; }
        public string PTEUSOYO { get; set; }
        public string LISREDYS { get; set; }
        public string LWWAS { get; set; }
        public string ANSTS { get; set; }
        public string HAPSTYS { get; set; }
        public string FMCRCOH { get; set; }
        public decimal nonta { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public int bkno { get; set; }
        public decimal VALAAUSFWK { get; set; }
        public decimal VALLINSTUS { get; set; }
        public decimal VALIVDRGUSE { get; set; }
        public decimal VALPTEDAWDD { get; set; }
        public decimal VALPTEDAWDE { get; set; }
        public decimal VALPTEDAWED { get; set; }
        public decimal VALPTEDAWEE { get; set; }
        public decimal VALPTEDOYO { get; set; }
        public decimal VALPTEUSWDD { get; set; }
        public decimal VALPTEUSWDE { get; set; }
        public decimal VALPTEUSWED { get; set; }
        public decimal VALPTEUSWEE { get; set; }
        public decimal VALPTEUSOYO { get; set; }
        public decimal VALLISREDYS { get; set; }
        public decimal VALLWWAS { get; set; }
        public decimal VALANSTS { get; set; }
        public decimal VALHAPSTYS { get; set; }
        public decimal VALFMCRCOH { get; set; }
        public string AFUCAN { get; set; }
        public string AFUALC { get; set; }
        public string AFUTOBN { get; set; }
        public string AFUOOL { get; set; }
        public string AFUCRACK { get; set; }
        public string AFUCOC { get; set; }
        public string AFUEST { get; set; }
        public string AFUAMP { get; set; }
        public string AFUSLV { get; set; }
        public string AFUKET { get; set; }
        public string AFUGHB { get; set; }
        public string AFULHU { get; set; }
        public string AFUTQL { get; set; }
        public int otherdrug { get; set; }
        public int otherdrug2 { get; set; }
        public int otherdrug3 { get; set; }
    }
}
