//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zparams
    {
        public decimal zparam { get; set; }
        public string repname { get; set; }
        public string fldname { get; set; }
        public string deflabel { get; set; }
        public string userlabel { get; set; }
        public Nullable<decimal> defpos { get; set; }
        public Nullable<decimal> userpos { get; set; }
        public Nullable<decimal> isvis { get; set; }
        public Nullable<decimal> defisvis { get; set; }
        public Nullable<decimal> can { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public Nullable<decimal> mno { get; set; }
    }
}
