//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zrepm435
    {
        public string serno { get; set; }
        public string name { get; set; }
        public string persno { get; set; }
        public Nullable<decimal> treat { get; set; }
        public Nullable<System.DateTime> triage { get; set; }
        public Nullable<System.DateTime> closed { get; set; }
        public Nullable<System.DateTime> refd { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string outcome { get; set; }
    }
}
