//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zsmsrem
    {
        public string srno { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime sms_dt { get; set; }
        public string time { get; set; }
        public string name { get; set; }
        public string persno { get; set; }
        public string htel { get; set; }
        public string otel { get; set; }
        public string sms_user { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
