//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zwatn1
    {
        public string srno { get; set; }
        public string fn { get; set; }
        public string sn { get; set; }
        public System.DateTime dob { get; set; }
        public string daat { get; set; }
        public string keyw { get; set; }
        public string office { get; set; }
        public string modality { get; set; }
        public string modnta { get; set; }
        public System.DateTime refd { get; set; }
        public System.DateTime modst { get; set; }
        public System.DateTime firstapp { get; set; }
        public decimal watdays { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
