//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZXMLASSHV5
    {
        public decimal CLT_CMS_ID { get; set; }
        public decimal DIR_CMS_ID { get; set; }
        public decimal DIR_O { get; set; }
        public decimal DIR_D { get; set; }
        public decimal DIR_ST { get; set; }
        public decimal DIR_S { get; set; }
        public decimal DIR_PD { get; set; }
        public string DIR000 { get; set; }
        public string DIR001 { get; set; }
        public System.DateTime DIR001A { get; set; }
        public string DIR001B { get; set; }
        public string DIR002 { get; set; }
        public string DIR003 { get; set; }
        public string DIR003A { get; set; }
        public System.DateTime DIR004 { get; set; }
        public string DIR005 { get; set; }
        public string DIR005A { get; set; }
        public string DIR006 { get; set; }
        public string DIR006A { get; set; }
        public string DIR007 { get; set; }
        public string DIR007A { get; set; }
        public System.DateTime DIR008 { get; set; }
        public string DIR009 { get; set; }
        public string DIR010 { get; set; }
        public string DIR011 { get; set; }
        public string DIR012 { get; set; }
        public string DIR012A { get; set; }
        public string DIR013 { get; set; }
        public string DIR013A { get; set; }
        public string DIR014 { get; set; }
        public System.DateTime DIR014A { get; set; }
        public string DIR014B { get; set; }
        public string DIR014C { get; set; }
        public string DIR015 { get; set; }
        public decimal CAN { get; set; }
        public System.DateTime EXPDATE { get; set; }
        public decimal EXPID { get; set; }
        public int srno { get; set; }
        public string DATCODE { get; set; }
    }
}
