//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zxmlichv21
    {
        public int srno { get; set; }
        public decimal CLTID { get; set; }
        public string IC001 { get; set; }
        public string IC001A { get; set; }
        public string IC002 { get; set; }
        public string IC500 { get; set; }
        public string IC003 { get; set; }
        public string IC004 { get; set; }
        public string IC005 { get; set; }
        public System.DateTime IC006 { get; set; }
        public string IC007 { get; set; }
        public string IC008 { get; set; }
        public string IC009 { get; set; }
        public string IC009A { get; set; }
        public string IC010 { get; set; }
        public decimal CAN { get; set; }
        public System.DateTime EXPDATE { get; set; }
        public decimal EXPID { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
