//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZXMLSPTRHV5
    {
        public decimal DIR_ST { get; set; }
        public decimal ID { get; set; }
        public string ST001 { get; set; }
        public System.DateTime ST002 { get; set; }
        public decimal CAN { get; set; }
        public System.DateTime EXPDATE { get; set; }
        public decimal EXPID { get; set; }
        public int srno { get; set; }
        public string DATCODE { get; set; }
    }
}
