//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zxmlrahv21
    {
        public int srno { get; set; }
        public decimal CLTID { get; set; }
        public decimal RAID { get; set; }
        public string RA001 { get; set; }
        public string RA001A { get; set; }
        public string RA001B { get; set; }
        public string RA002 { get; set; }
        public string RA500 { get; set; }
        public string RA003 { get; set; }
        public string RA004 { get; set; }
        public string RA005 { get; set; }
        public string RA006 { get; set; }
        public string RA007 { get; set; }
        public System.DateTime RA008 { get; set; }
        public System.DateTime RA008A { get; set; }
        public string RA009 { get; set; }
        public string RA010 { get; set; }
        public string RA010A { get; set; }
        public string RA011 { get; set; }
        public string RA011A { get; set; }
        public string RA012 { get; set; }
        public string RA013 { get; set; }
        public string RA013A { get; set; }
        public string RA013B { get; set; }
        public string RA014 { get; set; }
        public string RA014A { get; set; }
        public string RA014B { get; set; }
        public string RA014C { get; set; }
        public string RA014D { get; set; }
        public string RA015 { get; set; }
        public string RA016 { get; set; }
        public string RA016A { get; set; }
        public string RA017 { get; set; }
        public string RA017A { get; set; }
        public string RA018 { get; set; }
        public string RA019 { get; set; }
        public string RA019A { get; set; }
        public string RA019B { get; set; }
        public string RA019C { get; set; }
        public string RA019D { get; set; }
        public string RA020 { get; set; }
        public decimal CAN { get; set; }
        public System.DateTime EXPDATE { get; set; }
        public decimal EXPID { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
    }
}
