//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zxmlhist
    {
        public decimal expid { get; set; }
        public System.DateTime expdate { get; set; }
        public decimal can { get; set; }
        public string exptime { get; set; }
        public decimal xmlsubmit { get; set; }
        public string xmlexport { get; set; }
        public decimal user_id { get; set; }
        public decimal rollbackby { get; set; }
        public System.DateTime rollbackdt { get; set; }
        public decimal xmlsubmitby { get; set; }
        public System.DateTime xmlsubmitdt { get; set; }
        public string xmlresp { get; set; }
        public Nullable<decimal> mno { get; set; }
        public string user_upd { get; set; }
        public Nullable<System.DateTime> dtalter { get; set; }
        public string DATCODE { get; set; }
    }
}
