//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZXMLCLTHV5
    {
        public decimal CLT_CMS_ID { get; set; }
        public decimal CMS_ID { get; set; }
        public string CLT001 { get; set; }
        public string CLT002 { get; set; }
        public System.DateTime CLT003 { get; set; }
        public string CLT004 { get; set; }
        public string CLT006 { get; set; }
        public string CLT007 { get; set; }
        public string CLT007A { get; set; }
        public string CLT008 { get; set; }
        public string CLT009 { get; set; }
        public string CLT010 { get; set; }
        public string CLT011 { get; set; }
        public string CLT012 { get; set; }
        public decimal CAN { get; set; }
        public System.DateTime EXPDATE { get; set; }
        public decimal EXPID { get; set; }
        public int srno { get; set; }
        public string DATCODE { get; set; }
    }
}
