//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZXMLRAHV5
    {
        public decimal CLT_CMS_ID { get; set; }
        public decimal RA_CMS_ID { get; set; }
        public decimal ASSLEAD_ID { get; set; }
        public System.DateTime RA001 { get; set; }
        public string RA002 { get; set; }
        public string RA003 { get; set; }
        public System.DateTime RA004 { get; set; }
        public string RA005 { get; set; }
        public string RA005A { get; set; }
        public string RA006 { get; set; }
        public string RA007 { get; set; }
        public string RA007A { get; set; }
        public decimal CAN { get; set; }
        public System.DateTime EXPDATE { get; set; }
        public decimal EXPID { get; set; }
        public int srno { get; set; }
        public string DATCODE { get; set; }
    }
}
