//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZXMLACTHV5
    {
        public decimal CLT_CMS_ID { get; set; }
        public decimal ACT_CMS_ID { get; set; }
        public decimal ACT_ST { get; set; }
        public decimal ACT_SUP { get; set; }
        public decimal DIR_CMS_ID { get; set; }
        public System.DateTime ACT001 { get; set; }
        public System.DateTime ACT002 { get; set; }
        public string ACT003 { get; set; }
        public string ACT003A { get; set; }
        public string ACT003B { get; set; }
        public decimal CAN { get; set; }
        public System.DateTime EXPDATE { get; set; }
        public decimal EXPID { get; set; }
        public decimal ACTTYPE { get; set; }
        public int srno { get; set; }
        public string DATCODE { get; set; }
    }
}
